Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2018-08, with the labels that each got.

#3067 chore(package): update Babel dependencies
  .babel-preset.js
  package.json
  yarn.lock
Labels: chore

#3068 chore(package): use react 16.4 in docs and tests
  package.json
  test/specs/modules/Dropdown/Dropdown-test.js
  yarn.lock
Labels: chore

#3065 docs(Examples): use react-source-render
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleRenderEditor.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleRenderSource.js
  docs/src/components/ComponentDoc/ComponentExample/renderExampleSourceCode.js
  package.json
  yarn.lock
Labels: docs, ready for review

#3055 fix(Dropdown): fix `additionLabel` definition
  src/modules/Dropdown/Dropdown.d.ts
  test/typings.tsx
Labels: ready for merge, ready for review

#3052 fix(Sidebar): clear timer when unmounting
  src/modules/Sidebar/Sidebar.js
  test/specs/modules/Sidebar/Sidebar-test.js
Labels: ready for merge, ready for review

#3024 fix(Modal): prevent resize loop for full screen height
  src/modules/Modal/Modal.js
  test/specs/modules/Modal/Modal-test.js
Labels: ready for merge, ready for review

#3069 docs(perf): refactor ComponentControls
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.js
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCopyLink.js
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsEditCode.js
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsMaximize.js
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowHtml.js
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsToolTip.js
Labels: docs, ready for review

#3084 chore(package): bump react-sandbox-render
  package.json
  yarn.lock
Labels: chore

#3070 docs(ComponentExample): fix display of children
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
Labels: ready for review

#3086 chore(package): update Babel to RC1
  docs/src/index.js
  package.json
  yarn.lock
Labels: chore

#3082 docs(Item): cleanup examples
  docs/src/examples/views/Item/Content/ItemExampleExtraContent.js
  docs/src/examples/views/Item/Content/ItemExampleLink.js
  docs/src/examples/views/Item/Content/ItemExampleMetadata.js
  docs/src/examples/views/Item/Variations/ItemExampleDivided.js
Labels: ready for merge, ready for review

#3098 fix(docs): fix issues with local builds
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  gulp/plugins/gulp-example-source.js
  gulp/tasks/docs.js
Labels: ready for review
