Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2018-06, with the labels that each got.

#1542 chore(tests): fail on console activity
  index.d.ts
  karma.conf.babel.js
  src/addons/Select/Select.d.ts
  src/addons/Select/Select.js
  src/behaviors/Visibility/Visibility.js
  src/collections/Form/FormSelect.d.ts
  src/collections/Form/FormSelect.js
  src/modules/Embed/Embed.js
  src/modules/Popup/Popup.js
  src/modules/Progress/Progress.js
  test/setup.js
  test/specs/addons/Select/Select-test.js
  test/specs/collections/Form/Form-test.js
  test/specs/collections/Form/FormSelect-test.js
  test/specs/collections/Table/Table-test.js
  test/specs/collections/Table/TableRow-test.js
  test/specs/commonTests/implementsClassNameProps.js
  test/specs/commonTests/implementsCommonProps.js
  test/specs/commonTests/implementsCreateMethod.js
  test/specs/docs/examples-test.js
  test/specs/elements/Header/Header-test.js
  test/specs/elements/List/ListItem-test.js
  test/specs/lib/factories-test.js
  test/specs/modules/Dimmer/DimmerInner-test.js
  test/specs/modules/Dropdown/Dropdown-test.js
  test/specs/modules/Embed/Embed-test.js
  test/specs/modules/Modal/Modal-test.js
  test/specs/modules/Popup/Popup-test.js
  test/specs/modules/Search/Search-test.js
  test/specs/modules/Search/SearchResult-test.js
  test/tests.bundle.js
  test/utils/assertNodeContains.js
Labels: chore, ready for merge

#2859 test(Search): fix tests on second run
  test/specs/modules/Search/Search-test.js
Labels: ready for merge

#2817 feat(Dropdown): open to side with most space left #720
  docs/app/Examples/modules/Dropdown/Usage/index.js
  src/modules/Dropdown/Dropdown.d.ts
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: ready for merge

#2837 refactor(eventStack): make eventStack immutable
  src/lib/eventStack/EventPool.js
  src/lib/eventStack/EventSet.js
  src/lib/eventStack/EventStack.js
  src/lib/eventStack/EventTarget.js
  src/lib/eventStack/README.md
  src/lib/eventStack/eventStack.js
  src/lib/eventStack/index.js
  src/lib/eventStack/normalizeHandlers.js
  test/specs/lib/eventStack/EventPool-test.js
  test/specs/lib/eventStack/EventSet-test.js
  test/specs/lib/eventStack/EventStack-test.js
  test/specs/lib/eventStack/EventTarget-test.js
  test/specs/lib/eventStack/normalizeHandlers-test.js
Labels: chore, ready for merge

#2882 fix(Modal): remove dimmer={false}
  docs/src/examples/modules/Modal/Types/ModalExampleMultiple.js
  docs/src/examples/modules/Modal/Variations/ModalExampleCloseConfig.js
  docs/src/examples/modules/Modal/Variations/ModalExampleDimmer.js
  src/modules/Modal/Modal.d.ts
  src/modules/Modal/Modal.js
  test/specs/modules/Modal/Modal-test.js
Labels: ready for review

#2914 chore(package): update lint-stagged
  package.json
  yarn.lock
Labels: chore

#2909 fix(Search): wrap categorized search results with "results"
  src/modules/Search/SearchCategory.js
  test/specs/modules/Search/SearchCategory-test.js
Labels: ready for merge, ready for review

#2890 feat(Sticky): use SUI CSS classes
  src/modules/Sticky/Sticky.js
  test/specs/modules/Sticky/Sticky-test.js
Labels: enhancement, ready for review

#2885 fix(Dropdown): automatic upward logic in IE11
  src/modules/Dropdown/Dropdown.js
Labels: ready for review

#2929 fix(examples): webpack 3 App direct import description
  examples/webpack3/src/App.js
Labels: ready for review

#2845 feat(Sidebar): add lifecycle handlers
  docs/src/examples/modules/Sidebar/Examples/SidebarExampleMultiple.js
  docs/src/examples/modules/Sidebar/Examples/SidebarExampleTransitions.js
  docs/src/examples/modules/Sidebar/Examples/index.js
  docs/src/examples/modules/Sidebar/Overlay/SidebarExampleBottomOverlay.js
  docs/src/examples/modules/Sidebar/Overlay/SidebarExampleLeftOverlay.js
  docs/src/examples/modules/Sidebar/Overlay/SidebarExampleRightOverlay.js
  docs/src/examples/modules/Sidebar/Overlay/SidebarExampleTopOverlay.js
  docs/src/examples/modules/Sidebar/Overlay/index.js
  docs/src/examples/modules/Sidebar/Push/SidebarExampleBottomPush.js
  docs/src/examples/modules/Sidebar/Push/SidebarExampleLeftPush.js
  docs/src/examples/modules/Sidebar/Push/SidebarExampleRightPush.js
  docs/src/examples/modules/Sidebar/Push/index.js
  docs/src/examples/modules/Sidebar/ScaleDown/SidebarExampleBottomScaleDown.js
  docs/src/examples/modules/Sidebar/ScaleDown/SidebarExampleLeftScaleDown.js
  docs/src/examples/modules/Sidebar/ScaleDown/SidebarExampleRightScaleDown.js
  docs/src/examples/modules/Sidebar/ScaleDown/SidebarExampleTopScaleDown.js
  docs/src/examples/modules/Sidebar/ScaleDown/index.js
  docs/src/examples/modules/Sidebar/SlideAlong/SidebarExampleLeftSlideAlong.js
  docs/src/examples/modules/Sidebar/SlideAlong/SidebarExampleRightSlideAlong.js
  docs/src/examples/modules/Sidebar/SlideAlong/index.js
  docs/src/examples/modules/Sidebar/SlideOut/SidebarExampleLeftSlideOut.js
  docs/src/examples/modules/Sidebar/SlideOut/index.js
  docs/src/examples/modules/Sidebar/States/SidebarExampleDimmed.js
  docs/src/examples/modules/Sidebar/States/SidebarExampleVisible.js
  docs/src/examples/modules/Sidebar/States/index.js
  docs/src/examples/modules/Sidebar/Types/SidebarExampleSidebar.js
  docs/src/examples/modules/Sidebar/Types/index.js
  docs/src/examples/modules/Sidebar/Uncover/SidebarExampleLeftUncover.js
  docs/src/examples/modules/Sidebar/Uncover/SidebarExampleRightUncover.js
  docs/src/examples/modules/Sidebar/Uncover/index.js
  docs/src/examples/modules/Sidebar/Usage/SidebarExampleCallback.js
  docs/src/examples/modules/Sidebar/Usage/index.js
  docs/src/examples/modules/Sidebar/index.js
  src/modules/Sidebar/Sidebar.d.ts
  src/modules/Sidebar/Sidebar.js
  test/specs/commonTests/classNameHelpers.js
  test/specs/commonTests/hasUIClassName.js
  test/specs/commonTests/implementsClassNameProps.js
  test/specs/commonTests/isConformant.js
  test/specs/commonTests/rendersChildren.js
  test/specs/modules/Sidebar/Sidebar-test.js
  test/utils/index.js
  test/utils/nestedShallow.js
Labels: enhancement, ready for review

#2940 chore(package): use shallowequal instead of fbjs and use alias in docs
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/components/ComponentDoc/ContributionPrompt.js
  docs/src/components/ComponentDoc/ExampleSection.js
  docs/src/components/IconSearch/IconSearch.js
  docs/src/components/LayoutsLayout.js
  docs/src/components/Logo/Logo.js
  docs/src/examples/addons/Radio/Types/index.js
  docs/src/examples/collections/Form/Types/index.js
  docs/src/examples/collections/Form/Usage/index.js
  docs/src/examples/elements/Icon/index.js
  docs/src/hoc/updateForKeys.js
  docs/src/views/Introduction.js
  docs/src/views/PageNotFound.js
  docs/src/views/Usage.js
  package.json
  src/lib/shallowEqual.js
Labels: chore

#2941 chore(package): add `sideEffects: false` for Webpack 4
  docs/src/views/Usage.js
  package.json
Labels: chore

#2948 docs(Search): update layout for search example to accommodate code
  docs/src/examples/modules/Search/Types/SearchExampleCategory.js
  docs/src/examples/modules/Search/Types/SearchExampleStandard.js
Labels: docs, ready for review

#2947 fix(Icon): fix handling of aria-label
  src/elements/Icon/Icon.d.ts
  src/elements/Icon/Icon.js
  test/specs/elements/Icon/Icon-test.js
Labels: ready for review

#1918 feat(Dropdown): lazyLoad prop for menu items
  src/modules/Dropdown/Dropdown.d.ts
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: ready for merge, ready for review

#2958 fix(Portal): remove non-working `style` prop
  src/addons/Portal/Portal.d.ts
  src/addons/Portal/Portal.js
Labels: ready for merge, ready for review

#2880 BREAKING(package): update to React 16
  .eslintrc
  docs/src/components/ComponentDoc/ComponentDocLinks.js
  docs/src/components/IconSearch/IconSearch.js
  docs/src/examples/modules/Accordion/Advanced/AccordionExampleForm.js
  docs/src/examples/modules/Accordion/Advanced/AccordionExampleNested.js
  docs/src/examples/modules/Accordion/Advanced/AccordionExampleShorthand.js
  docs/src/examples/modules/Accordion/Types/AccordionExampleStandardShorthand.js
  docs/src/examples/modules/Accordion/Usage/AccordionExampleActiveIndex.js
  docs/src/examples/modules/Accordion/Usage/AccordionExampleExclusive.js
  docs/src/examples/modules/Modal/Variations/ModalExampleCloseConfig.js
  index.d.ts
  package.json
  src/addons/Portal/Portal.d.ts
  src/addons/Portal/Portal.js
  src/addons/Portal/PortalInner.d.ts
  src/addons/Portal/PortalInner.js
  src/elements/Flag/Flag.d.ts
  src/elements/Flag/Flag.js
  src/elements/Icon/Icon.d.ts
  src/elements/Icon/Icon.js
  src/index.js
  src/modules/Accordion/Accordion.js
  src/modules/Accordion/AccordionAccordion.d.ts
  src/modules/Accordion/AccordionAccordion.js
  src/modules/Accordion/AccordionPanel.d.ts
  src/modules/Accordion/AccordionPanel.js
  src/modules/Modal/Modal.js
  src/modules/Popup/Popup.js
  test/specs/addons/Portal/Portal-test.js
  test/specs/addons/Portal/PortalInner-test.js
  test/specs/modules/Accordion/Accordion-test.js
  test/specs/modules/Accordion/AccordionAccordion-test.js
  test/specs/modules/Accordion/AccordionPanel-test.js
  test/specs/modules/Popup/Popup-test.js
Labels: chore, ready for review
