Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2018-09, with the labels that each got.

#3131 chore(package): update deps
  package.json
  static.webpack.js
  test/specs/addons/Confirm/Confirm-test.js
  test/specs/addons/Portal/Portal-test.js
  test/specs/behaviors/Visibility/Visibility-test.js
  test/specs/collections/Breadcrumb/BreadcrumbDivider-test.js
  test/specs/collections/Form/FormField-test.js
  test/specs/collections/Menu/MenuItem-test.js
  test/specs/collections/Message/Message-test.js
  test/specs/commonTests/implementsCommonProps.js
  test/specs/commonTests/implementsShorthandProp.js
  test/specs/elements/Button/Button-test.js
  test/specs/elements/Header/Header-test.js
  test/specs/elements/Image/Image-test.js
  test/specs/elements/Input/Input-test.js
  test/specs/elements/Label/Label-test.js
  test/specs/elements/Step/Step-test.js
  test/specs/elements/Step/StepContent-test.js
  test/specs/modules/Accordion/AccordionPanel-test.js
  test/specs/modules/Checkbox/Checkbox-test.js
  test/specs/modules/Dropdown/Dropdown-test.js
  test/specs/modules/Dropdown/DropdownHeader-test.js
  test/specs/modules/Dropdown/DropdownItem-test.js
  test/specs/modules/Embed/Embed-test.js
  test/specs/modules/Modal/Modal-test.js
  test/specs/modules/Sticky/Sticky-test.js
  test/specs/views/Card/CardContent-test.js
  test/specs/views/Feed/FeedContent-test.js
  test/specs/views/Feed/FeedEvent-test.js
  test/specs/views/Feed/FeedLabel-test.js
  test/specs/views/Feed/FeedLike-test.js
  test/specs/views/Feed/FeedMeta-test.js
  test/specs/views/Feed/FeedSummary-test.js
  test/specs/views/Item/Item-test.js
  test/specs/views/Item/ItemContent-test.js
  test/specs/views/Stastistic/Statistic-test.js
  yarn.lock
Labels: chore

#3139 fix(customPropTypes): allow to pass an object to "as"
  src/lib/customPropTypes.js
Labels: ready for merge, ready for review

#3142 chore(build): fix prettier imports
  config.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleRenderEditor.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleRenderHtml.js
  docs/src/utils/formatCode.js
  docs/src/utils/index.js
  webpack.config.babel.js
Labels: chore

#3145 chore(package): update babel-plugin-filter-imports
  package.json
  yarn.lock
Labels: chore

#3104 fix(Dropdown): fix deepEqual bug
  src/modules/Dropdown/Dropdown.js
Labels: ready for merge, ready for review

#3109 fix(Popup): missing CSS style update
  src/modules/Popup/Popup.js
  test/specs/modules/Popup/Popup-test.js
Labels: ready for review

#3172 feat(Placeholder): add component
  docs/src/components/Document.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleHeader.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleHeaderImage.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleImage.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleImageShapeRectangular.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleImageShapeSquare.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleLine.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleParagraph.js
  docs/src/examples/elements/Placeholder/Content/index.js
  docs/src/examples/elements/Placeholder/Types/PlaceholderExampleCard.js
  docs/src/examples/elements/Placeholder/Types/PlaceholderExampleGrid.js
  docs/src/examples/elements/Placeholder/Types/PlaceholderExamplePlaceholder.js
  docs/src/examples/elements/Placeholder/Types/index.js
  docs/src/examples/elements/Placeholder/Variations/PlaceholderExampleFluid.js
  docs/src/examples/elements/Placeholder/Variations/PlaceholderExampleInverted.js
  docs/src/examples/elements/Placeholder/Variations/PlaceholderExampleLineLength.js
  docs/src/examples/elements/Placeholder/Variations/PlaceholderExampleLineLengthWithHeader.js
  docs/src/examples/elements/Placeholder/Variations/index.js
  docs/src/examples/elements/Placeholder/index.js
  index.d.ts
  src/elements/Placeholder/Placeholder.d.ts
  src/elements/Placeholder/Placeholder.js
  src/elements/Placeholder/PlaceholderHeader.d.ts
  src/elements/Placeholder/PlaceholderHeader.js
  src/elements/Placeholder/PlaceholderImage.d.ts
  src/elements/Placeholder/PlaceholderImage.js
  src/elements/Placeholder/PlaceholderLine.d.ts
  src/elements/Placeholder/PlaceholderLine.js
  src/elements/Placeholder/PlaceholderParagraph.d.ts
  src/elements/Placeholder/PlaceholderParagraph.js
  src/elements/Placeholder/index.d.ts
  src/elements/Placeholder/index.js
  src/index.js
  test/specs/elements/Placeholder/Placeholder-test.js
  test/specs/elements/Placeholder/PlaceholderHeader-test.js
  test/specs/elements/Placeholder/PlaceholderImage-test.js
  test/specs/elements/Placeholder/PlaceholderLine-test.js
  test/specs/elements/Placeholder/PlaceholderParagraph-test.js
Labels: enhancement, ready for review

#3179 docs(Advertisement): update a base Advertisement
  docs/src/components/Document.js
  docs/src/examples/views/Advertisement/Types/AdvertisementExampleAdvertisement.js
  docs/src/examples/views/Advertisement/Types/AdvertisementExampleStandard.js
  docs/src/examples/views/Advertisement/Types/index.js
Labels: docs

#3185 docs(props): improve parsing of customPropTypes.every()
  gulp/plugins/util/parseDocSection.js
  gulp/plugins/util/parserCustomHandler.js
  package.json
  yarn.lock
Labels: docs
