Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2018-05, with the labels that each got.

#2750 chore(package): use Babel 7
  .babelrc
  .prettierrc.json
  browser/index.html
  build/preset-env.js
  config.js
  docs/app/Components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/app/index.ejs
  package.json
  webpack.config.babel.js
  yarn.lock
Labels: ready for merge

#2761 chore(stalebot): update stalebot's messaging and timeframes
  .github/stale.yml
Labels: ready for review

#2784 chore(packge): upgrade to react-hot-loader 4
  docs/src/index.js
  package.json
  webpack.config.babel.js
  yarn.lock
Labels: v2

#2786 docs(ComponentDoc): wrap examples with Provider
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/examples/components/Layout/Types/LayoutExample.js
Labels: v2

#2789 feat(Provider): add Consumer subcomponent
  src/components/Provider/Provider.d.ts
  src/components/Provider/Provider.js
  src/components/Provider/ProviderConsumer.d.ts
  src/components/Provider/ProviderConsumer.js
  src/index.js
Labels: v2

#2792 fix(ComponentExample): fix href in copy link button
  docs/app/Components/ComponentDoc/ComponentExample/ComponentExample.js
Labels: ready for review

#2755 breaking(Portal): use createPortal() API
  .eslintrc
  docs/app/Components/IconSearch/IconSearch.js
  docs/app/Examples/modules/Modal/Variations/ModalExampleCloseConfig.js
  index.d.ts
  package.json
  src/addons/Portal/Portal.d.ts
  src/addons/Portal/Portal.js
  src/addons/Portal/PortalInner.d.ts
  src/addons/Portal/PortalInner.js
  src/index.js
  src/modules/Modal/Modal.js
  test/specs/addons/Portal/Portal-test.js
  test/specs/addons/Portal/PortalInner-test.js
Labels: enhancement, ready for review

#2782 feat(Image): add v2 Image component
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.js
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowVariables.js
  docs/src/components/ComponentDoc/ComponentDoc.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/components/ComponentDoc/ExampleSection.js
  docs/src/examples/components/Image/Types/ImageExample.js
  docs/src/examples/components/Image/Types/ImageExampleAvatar.js
  docs/src/examples/components/Image/Types/index.js
  docs/src/examples/components/Image/Variations/ImageExampleCircular.js
  docs/src/examples/components/Image/Variations/index.js
  docs/src/examples/components/Image/index.js
  docs/src/examples/components/Layout/index.js
  docs/src/utils/index.js
  gulp/tasks/docs.js
  src/components/Image/Image.js
  src/components/Image/imageRules.js
  src/components/Image/imageVariables.js
  src/components/Image/index.js
  src/components/Provider/Provider.js
  src/index.js
  src/lib/createComponent.js
  src/lib/getUnhandledProps.js
  src/lib/htmlPropsUtils.js
  src/lib/index.js
  src/umd.js
Labels: v2

#2796 fix(ComponentExample): clipboard and active state
  docs/app/Components/ComponentDoc/ComponentExample/ComponentExample.js
Labels: docs

#2800 fix(checkbox): pass disabled prop to input
  src/modules/Checkbox/Checkbox.js
  test/specs/modules/Checkbox/Checkbox-test.js
Labels: needs author feedback

#2775 fix(Popup) popup appearing in wrong position when open prop is set
  src/modules/Popup/Popup.js
  test/specs/modules/Popup/Popup-test.js
Labels: ready for merge

#2760 fix(docs): Fixing doc navigation link issues
  docs/app/Components/ComponentDoc/ComponentControls/ComponentControls.js
  docs/app/Components/ComponentDoc/ComponentDoc.js
  docs/app/Components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/app/Components/ComponentDoc/ComponentSidebar/ComponentSidebarSection.js
  docs/app/utils/exampleContext.js
  docs/app/utils/examplePathToHash.js
  docs/app/utils/getFormattedHash.js
  docs/app/utils/getNewHash.js
  docs/app/utils/index.js
  docs/app/utils/isOldHash.js
  docs/app/utils/parentComponents.js
Labels: ready for merge

#2424 feat(factories): add autoGenerateKey option
  docs/app/Components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/app/Examples/addons/Confirm/Types/ConfirmExampleConfirm.js
  docs/app/Examples/modules/Modal/Variations/ModalExampleScrollingContent.js
  src/addons/Confirm/Confirm.js
  src/collections/Breadcrumb/BreadcrumbDivider.js
  src/collections/Form/FormField.js
  src/collections/Menu/MenuItem.js
  src/collections/Message/Message.js
  src/elements/Button/Button.js
  src/elements/Header/Header.js
  src/elements/Image/Image.js
  src/elements/Input/Input.js
  src/elements/Label/Label.js
  src/elements/Label/LabelDetail.js
  src/elements/List/ListItem.js
  src/elements/Step/Step.js
  src/elements/Step/StepContent.js
  src/lib/factories.js
  src/modules/Checkbox/Checkbox.js
  src/modules/Dropdown/Dropdown.js
  src/modules/Dropdown/DropdownHeader.js
  src/modules/Dropdown/DropdownItem.js
  src/modules/Embed/Embed.js
  src/modules/Modal/Modal.js
  src/modules/Popup/Popup.js
  src/modules/Progress/Progress.js
  src/modules/Search/Search.js
  src/modules/Search/SearchResult.js
  src/modules/Tab/Tab.js
  src/views/Card/Card.js
  src/views/Card/CardContent.js
  src/views/Comment/CommentAvatar.js
  src/views/Feed/FeedContent.js
  src/views/Feed/FeedEvent.js
  src/views/Feed/FeedLabel.js
  src/views/Feed/FeedLike.js
  src/views/Feed/FeedMeta.js
  src/views/Feed/FeedSummary.js
  src/views/Item/Item.js
  src/views/Item/ItemContent.js
  src/views/Statistic/Statistic.js
  test/specs/commonTests/implementsShorthandProp.js
  test/specs/elements/Label/LabelDetail-test.js
  test/specs/lib/factories-test.js
Labels: ready for merge, ready for review

#2823 docs(Form): fix group variations typo
  docs/app/Examples/collections/Form/GroupVariations/index.js
Labels: ready for merge

#2803 feat(List): stub out v2 component
  .github/CONTRIBUTING.md
  docs/src/examples/components/List/Types/ListExample.js
  docs/src/examples/components/List/Types/ListExample.knobs.js
  docs/src/examples/components/List/Types/index.js
  docs/src/examples/components/List/index.js
  src/components/List/List.js
  src/components/List/ListItem.js
  src/components/List/index.js
  src/components/List/listItemRules.js
  src/components/List/listRules.js
  src/components/List/listVariables.js
  src/index.js
Labels: v2

#2832 chore(package): update babel to latest
  .babelrc
  package.json
  yarn.lock
Labels: chore

#2791 feat(Visibility): add `updateOn` prop
  docs/app/Examples/behaviors/Visibility/Settings/VisibilityExampleUpdateOn.js
  docs/app/Examples/behaviors/Visibility/Settings/index.js
  src/behaviors/Visibility/Visibility.d.ts
  src/behaviors/Visibility/Visibility.js
  test/specs/addons/Responsive/Responsive-test.js
  test/specs/behaviors/Visibility/Visibility-test.js
  test/specs/docs/examples-test.js
  test/specs/modules/Sticky/Sticky-test.js
Labels: enhancement, needs author feedback

#2833 chore(CI): use prebuilt image
  .circleci/config.yml
Labels: chore

#2850 chore(package): remove node-sass
  package.json
  yarn.lock
Labels: chore
