Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2018-07, with the labels that each got.

#2962 fix(Search): fix definition of resultRenderer prop in typings
  src/modules/Search/Search.d.ts
Labels: ready for merge, ready for review

#2928 feat(Input): expose select() method from ref
  src/elements/Input/Input.js
  test/specs/elements/Input/Input-test.js
Labels: ready for merge

#2985 docs(views): wrap each view with divs
  docs/src/views/Introduction.js
  docs/src/views/Layouts.js
  docs/src/views/PageNotFound.js
  docs/src/views/Theming.js
  docs/src/views/Usage.js
Labels: docs

#2986 docs(plugins): add a plugin for collect sources of examples
  .gitignore
  .prettierignore
  gulp/plugins/gulp-example-source.js
  gulp/tasks/docs.js
Labels: docs

#2982 fix(Input): add lang prop for input fields
  src/lib/htmlPropsUtils.js
Labels: ready for merge, ready for review

#2993 fix(Icon): add 'file text outline' type
  src/index.d.ts
  src/lib/SUI.js
Labels: ready for merge, ready for review

#2992 fix(EventStack): fix erroneous removal of non-empty EventPool
  src/lib/eventStack/EventPool.js
  src/lib/eventStack/EventTarget.js
  src/lib/eventStack/README.md
  test/specs/lib/eventStack/EventPool-test.js
  test/specs/lib/eventStack/EventStack-test.js
Labels: ready for merge, ready for review

#3014 docs(Layouts): fix size variables in HomepageLayout
  docs/src/layouts/HomepageLayout.js
Labels: docs

#3023 docs(Layouts): add new layout with Grid
  docs/public/images/examples/advanced-grid.png
  docs/src/layouts/AnotherGridLayout.js
  docs/src/layouts/index.js
  docs/src/views/Layouts.js
Labels: docs, ready for merge, ready for review

#3025 fix(Popup): removing dead line of code
  src/modules/Popup/Popup.js
Labels: ready for merge, ready for review

#3044 docs(src): fix Sidebar filter and Intro editors
  docs/src/Style.js
  docs/src/components/CarbonAd/CarbonAd.js
  docs/src/components/Sidebar/Sidebar.js
  docs/src/views/Introduction.js
Labels: docs
