Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2018-10, with the labels that each got.

#3188 feat(Dropdown): add `clearable` prop
  docs/src/examples/modules/Dropdown/Types/DropdownExampleClearable.js
  docs/src/examples/modules/Dropdown/Types/DropdownExampleClearableMultiple.js
  docs/src/examples/modules/Dropdown/Types/index.js
  src/modules/Dropdown/Dropdown.d.ts
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: enhancement

#3162 chore(package): update to SUI 2.4.0
  docs/src/components/Document.js
  docs/src/examples/elements/Flag/Types/FlagExampleTable.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleHeader.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleHeaderImage.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleImage.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleImageRectangular.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleImageSquare.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleLine.js
  docs/src/examples/elements/Placeholder/Content/PlaceholderExampleParagraph.js
  docs/src/examples/elements/Placeholder/Content/index.js
  docs/src/examples/elements/Placeholder/Types/PlaceholderExampleCard.js
  docs/src/examples/elements/Placeholder/Types/PlaceholderExampleGrid.js
  docs/src/examples/elements/Placeholder/Types/PlaceholderExamplePlaceholder.js
  docs/src/examples/elements/Placeholder/Types/index.js
  docs/src/examples/elements/Placeholder/Variations/PlaceholderExampleFluid.js
  docs/src/examples/elements/Placeholder/Variations/PlaceholderExampleInverted.js
  docs/src/examples/elements/Placeholder/Variations/PlaceholderExampleLineLength.js
  docs/src/examples/elements/Placeholder/Variations/PlaceholderExampleLineLengthWithHeader.js
  docs/src/examples/elements/Placeholder/Variations/index.js
  docs/src/examples/elements/Placeholder/index.js
  docs/src/examples/elements/Segment/Types/SegmentExamplePlaceholder.js
  docs/src/examples/elements/Segment/Types/SegmentExamplePlaceholderGrid.js
  docs/src/examples/elements/Segment/Types/SegmentExamplePlaceholderInline.js
  docs/src/examples/elements/Segment/Types/index.js
  docs/src/examples/modules/Dropdown/Types/DropdownExampleClearable.js
  docs/src/examples/modules/Dropdown/Types/DropdownExampleClearableMultiple.js
  docs/src/examples/modules/Dropdown/Types/index.js
  index.d.ts
  package.json
  src/elements/Flag/Flag.d.ts
  src/elements/Flag/Flag.js
  src/elements/Placeholder/Placeholder.d.ts
  src/elements/Placeholder/Placeholder.js
  src/elements/Placeholder/PlaceholderHeader.d.ts
  src/elements/Placeholder/PlaceholderHeader.js
  src/elements/Placeholder/PlaceholderImage.d.ts
  src/elements/Placeholder/PlaceholderImage.js
  src/elements/Placeholder/PlaceholderLine.d.ts
  src/elements/Placeholder/PlaceholderLine.js
  src/elements/Placeholder/PlaceholderParagraph.d.ts
  src/elements/Placeholder/PlaceholderParagraph.js
  src/elements/Placeholder/index.d.ts
  src/elements/Placeholder/index.js
  src/elements/Segment/Segment.d.ts
  src/elements/Segment/Segment.js
  src/elements/Segment/SegmentInline.d.ts
  src/elements/Segment/SegmentInline.js
  src/index.js
  src/modules/Dropdown/Dropdown.d.ts
  src/modules/Dropdown/Dropdown.js
  test/specs/elements/Placeholder/Placeholder-test.js
  test/specs/elements/Placeholder/PlaceholderHeader-test.js
  test/specs/elements/Placeholder/PlaceholderImage-test.js
  test/specs/elements/Placeholder/PlaceholderLine-test.js
  test/specs/elements/Placeholder/PlaceholderParagraph-test.js
  test/specs/elements/Segment/Segment-test.js
  test/specs/elements/Segment/SegmentInline-test.js
  test/specs/modules/Dropdown/Dropdown-test.js
  yarn.lock
Labels: chore

#2990 chore(Sidebar): use EventStack component
  src/modules/Sidebar/Sidebar.js
Labels: enhancement, ready for review

#3191 feat(Sidebar): add `target` prop
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleRenderSource.js
  docs/src/examples/modules/Sidebar/Usage/SidebarExampleTarget.js
  docs/src/examples/modules/Sidebar/Usage/index.js
  src/modules/Sidebar/Sidebar.d.ts
  src/modules/Sidebar/Sidebar.js
  test/specs/modules/Sidebar/Sidebar-test.js
Labels: enhancement

#3196 docs(mixed): add MDX support, update pages, styling updates
  docs/src/components/CodeEditor/CodeEditor.js
  docs/src/components/CodeEditor/CodeEditorUniveral.js
  docs/src/components/CodeEditor/index.js
  docs/src/components/CodeSnippet/CodeSnippet.js
  docs/src/components/CodeSnippet/index.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleRenderEditor.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleRenderHtml.js
  docs/src/components/DocumentationPage/DocumentationPage.js
  docs/src/components/DocumentationPage/components.js
  docs/src/components/DocumentationPage/index.js
  docs/src/components/Editor/index.js
  docs/src/pages/Introduction.js
  docs/src/pages/Layouts.mdx
  docs/src/pages/PageNotFound.js
  docs/src/pages/Theming.mdx
  docs/src/pages/Usage.mdx
  docs/src/staticUtils/requireInfo.js
  docs/src/views/Layouts.js
  docs/src/views/Theming.js
  docs/src/views/Usage.js
  docs/static/utils/getComponentGroupInfo.js
  docs/static/utils/getComponentMenu.js
  docs/static/utils/getExampleSources.js
  docs/static/utils/getInfoForSeeTags.js
  docs/static/utils/getLayoutPaths.js
  docs/static/utils/getPagesPaths.js
  docs/static/utils/getSidebarSections.js
  docs/static/utils/index.js
  docs/static/utils/requireInfo.js
  package.json
  static.config.js
  static.routes.js
  static.webpack.js
  yarn.lock
Labels: docs

#3203 docs(Prototypes): add example integration with redux-form
  docs/public/images/prototypes/redux-form.png
  docs/src/components/Sidebar/Sidebar.js
  docs/src/pages/Prototypes.mdx
Labels: docs

#3214 chore(build): update babel deps, fix production build of docs and build on Windows
  docs/src/components/Document.js
  gulp/sh.js
  gulp/tasks/dist.js
  gulpfile.js
  package.json
  static.config.js
  static.webpack.js
  yarn.lock
Labels: chore

#3215 docs(Ads): fix multiple ads
  docs/public/style.css
  docs/src/components/CarbonAd/CarbonAd.js
  docs/src/components/Sidebar/Sidebar.js
  docs/src/pages/Introduction.js
Labels: ready for review

#3218 docs(Ads): fix rendering in SSR
  docs/src/components/CarbonAd/CarbonAd.js
  docs/src/components/Document.js
  gulp/tasks/docs.js
  gulpfile.js
  package.json
Labels: ready for review

#3199 fix(Accordion): log error if incorrect activeIndex type
  src/modules/Accordion/AccordionAccordion.js
  test/specs/modules/Accordion/AccordionAccordion-test.js
Labels: ready for merge, ready for review

#3202 feat(Sticky): add `styleElement` prop
  src/modules/Sticky/Sticky.d.ts
  src/modules/Sticky/Sticky.js
  test/specs/modules/Sticky/Sticky-test.js
Labels: ready for merge, ready for review

#3032 BREAKING(package): require React 16.3
  docs/src/components/Document.js
  package.json
  src/addons/Portal/Portal.js
  src/modules/Accordion/AccordionPanel.js
  src/modules/Transition/TransitionGroup.js
  test/specs/commonTests/isConformant.js
  test/specs/modules/Accordion/AccordionPanel-test.js
  test/specs/modules/Transition/TransitionGroup-test.js
  yarn.lock
Labels: chore, ready for merge, ready for review
