Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2018-02, with the labels that each got.

#2495 docs(README): add 173app to the built with list
  README.md
Labels: ready for review

#2526 fix(ComponentDoc): clickable subcomponent props menu
  docs/app/Components/ComponentDoc/ComponentDoc.js
  docs/app/Components/ComponentDoc/ComponentExamples.js
  docs/app/Components/ComponentDoc/ComponentProps/ComponentPropsComponents.js
Labels: ready for merge

#2503 fix(Progress): use correct width for value/total
  docs/app/Examples/modules/Progress/Content/ProgressExampleProgressValuePercentageOfTotal.js
  docs/app/Examples/modules/Progress/Content/index.js
  src/modules/Progress/Progress.js
  test/specs/modules/Progress/Progress-test.js
Labels: needs author feedback

#2534 docs(TableExamplePagination): order icon names per docs
  docs/app/Examples/collections/Table/Types/TableExamplePagination.js
Labels: ready for merge

#2536 feat(Dropdown): add direction prop
  docs/app/Examples/modules/Dropdown/Variations/DropdownExampleMenuDirection.js
  docs/app/Examples/modules/Dropdown/Variations/index.js
  src/modules/Dropdown/Dropdown.d.ts
  src/modules/Dropdown/Dropdown.js
  src/modules/Dropdown/DropdownMenu.d.ts
  src/modules/Dropdown/DropdownMenu.js
  test/specs/modules/Dropdown/Dropdown-test.js
  test/specs/modules/Dropdown/DropdownMenu-test.js
Labels: ready for merge, ready for review

#2538 test(Portal): fix tests with timeouts
  test/specs/addons/TransitionablePortal/TransitionablePortal-test.js
  test/utils/assertWithTimeout.js
  test/utils/index.js
Labels: ready for merge, ready for review

#2481 docs(ComponentExample): fix code editor body regex
  docs/app/Components/ComponentDoc/ComponentExample/ComponentExample.js
Labels: needs author feedback

#2531 fix(Responsive): use root element client width
  src/addons/Responsive/Responsive.js
  test/specs/addons/Responsive/Responsive-test.js
Labels: ready for merge, ready for review

#2533 feat(Dropdown): 'wrapSelecion' prop: option to disable "infinity" list
  docs/app/Examples/modules/Dropdown/Usage/DropdownExampleWrapSelectionFalse.js
  docs/app/Examples/modules/Dropdown/Usage/index.js
  src/modules/Dropdown/Dropdown.d.ts
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: needs author feedback

#2537 fix(Pagination): allow to override props in PaginationItem
  src/addons/Pagination/PaginationItem.d.ts
  src/addons/Pagination/PaginationItem.js
  test/specs/addons/Pagination/PaginationItem-test.js
Labels: ready for review

#2562 fix(Card): fix typo in CardExampleLinkCardProp
  docs/app/Examples/views/Card/Content/CardExampleLinkCardProp.js
Labels: ready for merge, ready for review

#2568 fix(Accordion): update signature of `onTitleClick` in typings
  src/modules/Accordion/AccordionAccordion.d.ts
Labels: ready for merge, ready for review

#2554 fix(Layouts): fix typo in HomepageLayout
  docs/app/Layouts/HomepageLayout.js
Labels: ready for merge

#2576 fix(Transition): add slide left
  docs/app/Examples/addons/TransitionablePortal/Usage/TransitionablePortalExampleTransition.js
  docs/app/Examples/modules/Transition/Explorers/TransitionExampleGroupExplorer.js
  src/index.d.ts
  src/lib/SUI.js
Labels: ready for merge, ready for review
