Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2018-04, with the labels that each got.

#2621 feat(Responsive): add getWidth prop, fix perf
  src/addons/Responsive/Responsive.d.ts
  src/addons/Responsive/Responsive.js
  test/specs/addons/Responsive/Responsive-test.js
Labels: enhancement, needs author feedback

#2690 breaking(Modal): Fix vertical position with SUI 2.3
  docs/app/Examples/modules/Modal/Types/ModalExampleTopAligned.js
  docs/app/Examples/modules/Modal/Types/index.js
  package.json
  src/addons/Portal/Portal.d.ts
  src/addons/Portal/Portal.js
  src/modules/Modal/Modal.d.ts
  src/modules/Modal/Modal.js
  yarn.lock
Labels: ready for merge

#2597 chore(package): Prettier integration
  .prettierignore
  .prettierrc.json
  package.json
  yarn.lock
Labels: ready for merge, ready for review

#2739 docs(Table): rename TableExampleStriped example
  docs/app/Examples/collections/Table/Types/TableExampleCelledStriped.js
  docs/app/Examples/collections/Table/Types/index.js
Labels: ready for merge, ready for review

#2738 feat(Dropdown): allow to enable autoComplete on DropdownSearchInput
  src/modules/Dropdown/DropdownSearchInput.d.ts
  src/modules/Dropdown/DropdownSearchInput.js
  test/specs/modules/Dropdown/DropdownSearchInput-test.js
Labels: enhancement, ready for review

#2752 feat(Button): add role prop
  src/elements/Button/Button.d.ts
  src/elements/Button/Button.js
  test/specs/elements/Button/Button-test.js
Labels: ready for review

#2707 chore(package): use keyboard-key package
  .eslintrc
  docs/app/Components/Sidebar/Sidebar.js
  package.json
  src/addons/Pagination/PaginationItem.js
  src/addons/Portal/Portal.js
  src/lib/index.js
  src/lib/keyboardKey.js
  src/modules/Dropdown/Dropdown.js
  src/modules/Rating/RatingIcon.js
  src/modules/Search/Search.js
  test/specs/addons/Confirm/Confirm-test.js
  test/specs/lib/keyboardKey-test.js
  test/specs/modules/Rating/RatingIcon-test.js
  yarn.lock
Labels: ready for merge
