Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2018-11, with the labels that each got.

#3257 fix(Portal): hover behavior fixed in Portal's event handlers
  src/addons/Portal/Portal.js
  test/specs/addons/Portal/Portal-test.js
Labels: ready for merge

#3269 docs(Textarea): add notice about form
  docs/src/examples/addons/TextArea/Types/index.js
Labels: docs

#3270 docs(Divider): rework component docs
  docs/src/examples/elements/Divider/Types/DividerExampleHorizontal.js
  docs/src/examples/elements/Divider/Types/DividerExampleHorizontalTable.js
  docs/src/examples/elements/Divider/Types/DividerExampleVertical.js
  docs/src/examples/elements/Divider/Types/DividerExampleVerticalForm.js
  docs/src/examples/elements/Divider/Types/index.js
  docs/src/examples/elements/Divider/Variations/DividerExampleClearing.js
  docs/src/examples/elements/Divider/Variations/DividerExampleFitted.js
  docs/src/examples/elements/Divider/Variations/DividerExampleHidden.js
  docs/src/examples/elements/Divider/Variations/DividerExampleInverted.js
  docs/src/examples/elements/Divider/Variations/DividerExampleSection.js
Labels: docs

#3285 chore(package): use `shallowequal` directly
  docs/src/components/Sidebar/Sidebar.js
  src/addons/Responsive/Responsive.js
  src/lib/index.js
  src/lib/shallowEqual.js
  src/modules/Dropdown/Dropdown.js
  src/modules/Search/Search.js
Labels: chore

#3286 feat(Ref): add support of `createRef` API
  docs/src/examples/addons/Ref/Types/RefExampleRef.js
  src/addons/Portal/Portal.js
  src/addons/Ref/Ref.d.ts
  src/addons/Ref/Ref.js
  src/elements/Input/Input.js
  src/lib/handleRef.js
  src/lib/index.js
  src/modules/Dropdown/DropdownSearchInput.d.ts
  src/modules/Dropdown/DropdownSearchInput.js
  test/specs/lib/handleRef-test.js
Labels: enhancement

#3288 chore(package): update event-stack
  package.json
  yarn.lock
Labels: chore

#3274 feat(Responsive): re render only on visibility or props change
  src/addons/Responsive/Responsive.js
  src/addons/Responsive/lib/isVisible.js
  test/setup.js
  test/specs/addons/Responsive/Responsive-test.js
Labels: ready for merge, ready for review

#3301 fix(Popup): remove logic with setSafeState()
  src/modules/Popup/Popup.js
Labels: ready for merge, ready for review

#3315 feat(Icon): support positions in `corner` prop
  docs/src/examples/elements/Icon/Groups/IconExampleCornerGroupPositions.js
  docs/src/examples/elements/Icon/Groups/index.js
  src/elements/Icon/Icon.js
  test/specs/elements/Icon/Icon-test.js
Labels: enhancement
