Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2019-02, with the labels that each got.

#3425 fix(Checkbox): disable click on mouse right/middle button
  src/modules/Checkbox/Checkbox.js
  test/specs/modules/Checkbox/Checkbox-test.js
Labels: ready for merge

#3417 feat(Accordion): add `icon` shorthand for AccordionTitle
  docs/src/examples/modules/Accordion/Advanced/AccordionExampleIconShorthand.js
  docs/src/examples/modules/Accordion/Advanced/index.js
  docs/src/examples/modules/Accordion/Types/AccordionExampleStandardShorthand.js
  src/modules/Accordion/AccordionTitle.d.ts
  src/modules/Accordion/AccordionTitle.js
  test/specs/modules/Accordion/AccordionTitle-test.js
Labels: enhancement

#3420 docs(Portal): fix controlled Portal usage
  docs/src/examples/addons/Portal/Types/PortalExampleControlled.js
Labels: docs, ready for merge

#3428 chore(Dropdown): use EventStack component
  src/modules/Dropdown/Dropdown.js
Labels: chore

#3430 fix(Dropdown): sets focus to the search input after selection
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: ready for review

#3438 feat(Transition): allow custom animations
  src/modules/Transition/Transition.d.ts
  src/modules/Transition/Transition.js
  src/modules/Transition/TransitionGroup.d.ts
  src/modules/Transition/TransitionGroup.js
  test/specs/modules/Transition/Transition-test.js
  test/specs/modules/Transition/TransitionGroup-test.js
Labels: enhancement, ready for review

#3448 feat(Sticky): accept refs as value for `context` and `scrollContext` props
  docs/src/components/ComponentDoc/ComponentDoc.js
  docs/src/examples/behaviors/Visibility/Settings/VisibilityExampleCallbackFrequency.js
  docs/src/examples/behaviors/Visibility/Settings/VisibilityExampleGroupedCallbacks.js
  docs/src/examples/behaviors/Visibility/Settings/VisibilityExampleOffset.js
  docs/src/examples/behaviors/Visibility/Settings/VisibilityExampleUpdateOn.js
  docs/src/examples/behaviors/Visibility/Types/VisibilityExampleVisibility.js
  docs/src/examples/modules/Sticky/Types/StickyExampleAdjacentContext.js
  docs/src/examples/modules/Sticky/Types/StickyExamplePushing.js
  docs/src/examples/modules/Sticky/Usage/StickyExampleOffset.js
  docs/src/examples/modules/Sticky/Variations/StickyExampleActive.js
  docs/src/examples/modules/Sticky/Variations/StickyExampleOversized.js
  src/addons/Ref/RefFindNode.js
  src/addons/Ref/RefForward.js
  src/lib/customPropTypes.js
  src/lib/index.js
  src/lib/refUtils.js
  src/modules/Sticky/Sticky.d.ts
  src/modules/Sticky/Sticky.js
  test/specs/lib/refUtils-test.js
  test/specs/modules/Sticky/Sticky-test.js
Labels: enhancement

#3435 fix(Checkbox): prevent click propagation from the input element
  src/modules/Checkbox/Checkbox.js
  test/specs/commonTests/isConformant.js
  test/specs/modules/Checkbox/Checkbox-test.js
  test/utils/domEvent.js
Labels: ready for review

#3449 feat(MountNode): support refs as value for `node` prop
  docs/src/examples/addons/MountNode/Types/MountNodeExampleMountNode.js
  src/addons/MountNode/MountNode.d.ts
  src/addons/MountNode/MountNode.js
  src/addons/MountNode/lib/NodeRegistry.js
  src/addons/MountNode/lib/getNodeFromProps.js
  src/addons/MountNode/lib/getNodeRefFromProps.js
  src/addons/MountNode/lib/handleClassNamesChange.js
  src/lib/customPropTypes.js
  src/lib/index.js
  src/lib/refUtils.js
  src/modules/Sticky/Sticky.js
  test/specs/addons/MountNode/lib/getNodeFromProps-test.js
  test/specs/addons/MountNode/lib/getNodeRefFromProps-test.js
  test/specs/addons/MountNode/lib/handleClassNamesChange-test.js
  test/specs/lib/refUtils-test.js
Labels: enhancement

#3451 feat(Sidebar): support object refs as value for `target` prop
  docs/src/examples/modules/Sidebar/Usage/SidebarExampleTarget.js
  package.json
  src/modules/Sidebar/Sidebar.d.ts
  src/modules/Sidebar/Sidebar.js
  yarn.lock
Labels: enhancement

#3453 chore(Input|TextArea): use createRef() API
  src/addons/TextArea/TextArea.js
  src/elements/Input/Input.js
  test/specs/elements/Input/Input-test.js
Labels: chore

#3454 BREAKING(Portal): use createRef() API internally
  src/addons/Portal/Portal.d.ts
  src/addons/Portal/Portal.js
  src/addons/Portal/PortalInner.d.ts
  src/addons/Portal/PortalInner.js
  test/specs/addons/Portal/Portal-test.js
  test/specs/addons/Portal/PortalInner-test.js
Labels: breaking-change, enhancement

#3455 chore(Sidebar|Visibility): use createRef() API internally
  docs/src/examples/elements/Button/Usage/ButtonExampleFocus.js
  docs/src/examples/elements/Input/Usage/InputExampleRefFocus.js
  src/behaviors/Visibility/Visibility.js
  src/modules/Sidebar/Sidebar.js
  test/specs/behaviors/Visibility/Visibility-test.js
Labels: chore

#3457 chore(Modal): use createRef() API internally
  src/modules/Modal/Modal.js
Labels: chore

#3458 chore(Dropdown): use createRef() internally
  src/modules/Dropdown/Dropdown.js
  src/modules/Dropdown/DropdownSearchInput.d.ts
  src/modules/Dropdown/DropdownSearchInput.js
  test/specs/modules/Dropdown/Dropdown-test.js
  test/specs/modules/Dropdown/DropdownSearchInput-test.js
Labels: chore

#3459 feat(Popup): support an object from `createRef()` as context value
  docs/src/examples/modules/Popup/Usage/PopupExampleContext.js
  docs/src/examples/modules/Popup/Usage/PopupExampleContextControlled.js
  src/modules/Popup/Popup.d.ts
  src/modules/Popup/Popup.js
Labels: enhancement

#3460 chore(Button): use createRef() API internally
  src/elements/Button/Button.js
Labels: chore

#3465 breaking(TextArea): remove `autoHeight` prop
  docs/public/images/prototypes/react-textarea-autosize.png
  docs/src/examples/addons/TextArea/Usage/TextAreaExampleAutoHeight.js
  docs/src/examples/addons/TextArea/Usage/TextAreaExampleAutoHeightMinHeight.js
  docs/src/examples/addons/TextArea/Usage/TextAreaExampleAutoHeightRows.js
  docs/src/examples/addons/TextArea/Usage/index.js
  docs/src/pages/Prototypes.mdx
  src/addons/TextArea/TextArea.d.ts
  src/addons/TextArea/TextArea.js
  test/specs/addons/TextArea/TextArea-test.js
Labels: breaking-change

#3456 fix(Search): prevent blur event when SearchResult is clicked
  src/modules/Search/Search.js
  test/specs/modules/Search/Search-test.js
Labels: ready for merge
