Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2019-07, with the labels that each got.

#3684 fix(Sidebar): fix hide animation
  src/modules/Sidebar/Sidebar.js
Labels: ready for review

#3586 fix(Dropdown): use `placeholder` as default text
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: ready for review

#3679 fix(Modal): support IE11, fix scrolling glitches
  src/modules/Modal/Modal.js
  src/modules/Modal/utils/index.js
  test/specs/addons/MountNode/lib/NodeRegistry-test.js
  test/specs/addons/Portal/PortalInner-test.js
  test/specs/collections/Grid/GridColumn-test.js
  test/specs/elements/Step/StepContent-test.js
  test/specs/modules/Modal/Modal-test.js
  test/specs/modules/Modal/utils/canFit-test.js
  test/specs/modules/Modal/utils/getLegacyStyles-test.js
Labels: ready for review

#3693 fix(Checkbox): handle change on root element
  src/modules/Checkbox/Checkbox.js
  test/specs/modules/Checkbox/Checkbox-test.js
Labels: ready for review

#3707 docs(Composition|Shorthand): improve pages
  docs/src/components/Sidebar/Sidebar.js
  docs/src/pages/Augmentation.mdx
  docs/src/pages/ShorthandProps.mdx
  docs/src/pages/Usage.mdx
  package.json
  yarn.lock
Labels: docs

#3715 feat(Popup): add `eventsEnabled` prop
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleKnobs.js
  docs/src/components/ComponentDoc/ExampleEditor/renderConfig.js
  docs/src/components/ExternalExampleLayout.js
  docs/src/examples/modules/Popup/Usage/PopupExampleActions.js
  docs/src/examples/modules/Popup/Usage/PopupExampleEventsEnabled.js
  docs/src/examples/modules/Popup/Usage/index.js
  src/modules/Popup/Popup.d.ts
  src/modules/Popup/Popup.js
  test/specs/modules/Popup/Popup-test.js
Labels: enhancement, ready for review
