Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2019-09, with the labels that each got.

#3766 fix(Dropdown): closing the search menu on spacebar press
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: ready for review

#3774 chore(Ref): use component from Stardust UI
  docs/src/examples/addons/Ref/Types/RefExampleRef.js
  docs/src/examples/addons/Ref/Types/RefForwardingExample.js
  docs/src/examples/addons/Ref/Types/index.js
  docs/src/examples/addons/Ref/index.js
  index.d.ts
  package.json
  src/addons/MountNode/lib/getNodeRefFromProps.js
  src/addons/Portal/Portal.js
  src/addons/Portal/PortalInner.js
  src/addons/Ref/Ref.d.ts
  src/addons/Ref/Ref.js
  src/addons/Ref/RefFindNode.d.ts
  src/addons/Ref/RefFindNode.js
  src/addons/Ref/RefForward.d.ts
  src/addons/Ref/RefForward.js
  src/addons/Ref/index.d.ts
  src/addons/Ref/index.js
  src/addons/TextArea/TextArea.js
  src/behaviors/Visibility/Visibility.js
  src/elements/Button/Button.js
  src/elements/Input/Input.js
  src/index.js
  src/lib/index.js
  src/lib/refUtils.js
  src/modules/Checkbox/Checkbox.js
  src/modules/Dimmer/DimmerInner.js
  src/modules/Dropdown/Dropdown.js
  src/modules/Modal/Modal.js
  src/modules/Popup/Popup.js
  src/modules/Popup/lib/createReferenceProxy.js
  src/modules/Sidebar/Sidebar.js
  src/modules/Sticky/Sticky.js
  test/specs/addons/Ref/Ref-test.js
  test/specs/addons/Ref/RefFindNode-test.js
  test/specs/addons/Ref/RefForward-test.js
  test/specs/addons/Ref/fixtures.js
  test/specs/lib/refUtils-test.js
  test/utils/nestedShallow.js
  tsconfig.json
  yarn.lock
Labels: chore

#3772 fix(Sidebar): handle clicks properly
  docs/src/examples/modules/Sidebar/Examples/SidebarExampleMultiple.js
  docs/src/examples/modules/Sidebar/States/SidebarExampleDimmed.js
  docs/src/examples/modules/Sidebar/Types/SidebarExampleSidebar.js
  docs/src/examples/modules/Sidebar/Usage/SidebarExampleCallback.js
  docs/src/examples/modules/Sidebar/Usage/SidebarExampleTarget.js
  package.json
  src/modules/Dropdown/DropdownItem.js
  src/modules/Sidebar/Sidebar.js
  test/specs/modules/Dropdown/DropdownItem-test.js
  test/specs/modules/Sidebar/Sidebar-test.js
  yarn.lock
Labels: ready for review, wip
