Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2019-06, with the labels that each got.

#3651 docs(Examples): reduce number of items in examples, fix HMR issues
  docs/src/components/CodeEditor/CodeEditor.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/components/ComponentDoc/ExampleEditor/ExampleEditor.js
  docs/src/examples/addons/Select/Types/SelectExample.js
  docs/src/examples/modules/Dropdown/Types/DropdownExampleClearableMultiple.js
  docs/src/examples/modules/Dropdown/Types/DropdownExampleSearchSelection.js
  package.json
  yarn.lock
Labels: docs

#3632 feat(Dropdown): add 'closeOnEscape' prop
  docs/src/examples/modules/Dropdown/Usage/DropdownExampleCloseOnEscape.js
  docs/src/examples/modules/Dropdown/Usage/index.js
  src/modules/Dropdown/Dropdown.d.ts
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: enhancement

#3654 feat(Popup): add pinned and popperModifiers prop
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/examples/modules/Popup/States/PopupExamplePinned.js
  docs/src/examples/modules/Popup/States/index.js
  src/modules/Popup/Popup.d.ts
  src/modules/Popup/Popup.js
  test/specs/modules/Popup/Popup-test.js
Labels: enhancement, ready for merge

#3652 docs(mixed): improve perf & bundle size, fix issue with /layouts
  docs/public/style.css
  docs/src/App.js
  docs/src/components/CodeEditor/CodeEditor.js
  docs/src/components/CodeEditor/index.js
  docs/src/components/CodeSnippet/CodeSnippet.js
  docs/src/components/Document.js
  docs/src/pages/Introduction.js
  docs/src/pages/ShorthandProps.mdx
  docs/src/pages/Theming.mdx
  docs/src/pages/Usage.mdx
  package.json
  static.config.js
  static.webpack.js
  yarn.lock
Labels: docs

#3657 feat(Popup): add `popperDependencies` prop
  docs/src/examples/modules/Popup/Usage/PopupExamplePopperDependencies.js
  docs/src/examples/modules/Popup/Usage/index.js
  src/modules/Popup/Popup.d.ts
  src/modules/Popup/Popup.js
  test/specs/modules/Popup/Popup-test.js
Labels: enhancement, ready for review

#3680 feat(Label): add `prompt` prop
  docs/src/examples/elements/Label/Types/LabelExamplePrompt.js
  docs/src/examples/elements/Label/Types/index.js
  src/elements/Label/Label.d.ts
  src/elements/Label/Label.js
  test/specs/elements/Label/Label-test.js
Labels: enhancement

#3603 feat(Form): make `error` prop shorthand in Form.Field
  docs/src/examples/collections/Form/States/FormExampleFieldErrorLabel.js
  docs/src/examples/collections/Form/States/index.js
  src/collections/Form/FormDropdown.d.ts
  src/collections/Form/FormField.d.ts
  src/collections/Form/FormField.js
  src/collections/Form/FormInput.d.ts
  src/collections/Form/FormSelect.d.ts
  src/lib/factories.js
  test/specs/collections/Form/FormDropdown-test.js
  test/specs/collections/Form/FormField-test.js
  test/specs/collections/Form/FormInput-test.js
  test/specs/collections/Form/FormSelect-test.js
Labels: enhancement, ready for review
