Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2019-03, with the labels that each got.

#3488 docs(Breadcrumb): rework and clarify component examples
  docs/src/examples/collections/Breadcrumb/Content/BreadcrumbExampleDividerShorthand.js
  docs/src/examples/collections/Breadcrumb/Content/BreadcrumbExampleIconDividerProps.js
  docs/src/examples/collections/Breadcrumb/Content/BreadcrumbExampleSectionShorthand.js
  docs/src/examples/collections/Breadcrumb/Content/index.js
  docs/src/examples/collections/Breadcrumb/Types/BreadcrumbExample.js
  docs/src/examples/collections/Breadcrumb/Types/BreadcrumbExampleDivider.js
  docs/src/examples/collections/Breadcrumb/Types/BreadcrumbExampleShorthand.js
  docs/src/examples/collections/Breadcrumb/Types/index.js
  docs/src/examples/collections/Breadcrumb/Variations/BreadcrumbExampleBigSize.js
  docs/src/examples/collections/Breadcrumb/Variations/BreadcrumbExampleHugeSize.js
  docs/src/examples/collections/Breadcrumb/Variations/BreadcrumbExampleLargeSize.js
  docs/src/examples/collections/Breadcrumb/Variations/BreadcrumbExampleMassiveSize.js
  docs/src/examples/collections/Breadcrumb/Variations/BreadcrumbExampleMiniSize.js
  docs/src/examples/collections/Breadcrumb/Variations/BreadcrumbExampleSize.js
  docs/src/examples/collections/Breadcrumb/Variations/BreadcrumbExampleSmallSize.js
  docs/src/examples/collections/Breadcrumb/Variations/BreadcrumbExampleTinySize.js
  docs/src/examples/collections/Breadcrumb/Variations/index.js
Labels: docs

#3482 fix(Dropdown): not calls `onChange` when value is not changed on item click
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: ready for review

#3497 perf(docs): improve doc examples performance
  docs/public/style.css
  docs/src/components/CarbonAd/CarbonAdNative.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleTitle.js
  docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebar.js
Labels: docs

#3515 fix(Portal): fix `target` for `mouseEnter`/`mouselLeave` events
  src/addons/Portal/Portal.js
Labels: ready for review

#3522 docs(Dropdown): fix floating example in FF
  docs/src/examples/modules/Dropdown/Types/DropdownExampleFloating.js
Labels: docs

#3500 fix(Sticky): preserve item height
  docs/src/examples/modules/Sticky/Usage/StickyExampleAboveContent.js
  docs/src/examples/modules/Sticky/Usage/index.js
  src/modules/Sticky/Sticky.js
  test/specs/modules/Sticky/Sticky-test.js
Labels: ready for review

#3524 docs(mixed): add gender other to gender selectors
  docs/src/examples/collections/Form/Shorthand/FormExampleFieldControl.js
  docs/src/examples/collections/Form/Shorthand/FormExampleFieldControlId.js
  docs/src/examples/collections/Form/Shorthand/FormExampleSubcomponentControl.js
  docs/src/examples/collections/Form/States/FormExampleFieldError.js
  docs/src/examples/collections/Table/Variations/TableExampleColumnCount.js
  docs/src/examples/collections/Table/Variations/TableExampleSortable.js
Labels: docs

#3532 breaking(Popup): switch to Popper.js
  docs/src/App.js
  docs/src/components/Document.js
  docs/src/examples/modules/Popup/Types/PopupExample.js
  docs/src/examples/modules/Popup/Types/PopupExampleHeader.js
  docs/src/examples/modules/Popup/Types/PopupExampleHtml.js
  docs/src/examples/modules/Popup/Types/PopupExampleTrigger.js
  docs/src/examples/modules/Popup/Types/index.js
  docs/src/examples/modules/Popup/Usage/PopupExampleActions.js
  docs/src/examples/modules/Popup/Usage/PopupExampleClick.js
  docs/src/examples/modules/Popup/Usage/PopupExampleContext.js
  docs/src/examples/modules/Popup/Usage/PopupExampleControlled.js
  docs/src/examples/modules/Popup/Usage/PopupExampleDefaultOpen.js
  docs/src/examples/modules/Popup/Usage/PopupExampleFocus.js
  docs/src/examples/modules/Popup/Usage/PopupExampleHideOnScroll.js
  docs/src/examples/modules/Popup/Usage/PopupExampleHover.js
  docs/src/examples/modules/Popup/Usage/PopupExampleOffset.js
  docs/src/examples/modules/Popup/Usage/index.js
  docs/src/examples/modules/Popup/Variations/PopupExampleInverted.js
  docs/src/examples/modules/Popup/Variations/PopupExampleSize.js
  docs/src/examples/modules/Popup/Variations/PopupExampleWide.js
  docs/src/examples/modules/Popup/Variations/index.js
  gulp/plugins/util/parseType.js
  package.json
  src/modules/Popup/Popup.d.ts
  src/modules/Popup/Popup.js
  src/modules/Popup/lib/createReferenceProxy.js
  src/modules/Popup/lib/positions.js
  test/specs/modules/Popup/Popup-test.js
  yarn.lock
Labels: wip

#3533 docs(ComponentExample): replace deprecated lifecycle methods
  docs/src/components/ComponentDoc/ComponentDoc.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/utils/getFormattedHash.js
  docs/src/utils/index.js
  static.routes.js
Labels: ready for review

#3535 docs(ComponentDoc): replace deprecated lifecycle methods
  docs/src/components/ComponentDoc/ComponentDoc.js
Labels: ready for review
