Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2019-01, with the labels that each got.

#3354 docs(Responsive): update ResponsiveExampleMaxWidth.js (added two words to clarify)
  docs/src/examples/addons/Responsive/Types/ResponsiveExampleMaxWidth.js
Labels: docs

#3358 feat(Icon): `disabled` prop disables `onClick`
  src/elements/Icon/Icon.js
  test/specs/elements/Icon/Icon-test.js
Labels: enhancement

#3324 chore(build): drop DLL stage
  .eslintignore
  .gitignore
  .prettierignore
  config.js
  gulp/tasks/dll.js
  gulpfile.js
  karma.conf.babel.js
  package.json
  test/specs/docs/examples-test.js
  webpack.config.babel.js
  webpack.dll.js
  webpack.karma.config.js
  webpack.umd.config.js
Labels: chore

#3372 docs(Prototypes): add examples with `pure-react-carousel`
  docs/public/images/prototypes/pure-react-carousel.png
  docs/src/pages/Prototypes.mdx
Labels: docs

#3373 docs(Responsive): clarify SSR usage
  docs/src/examples/addons/Responsive/Usage/index.js
  docs/src/layouts/HomepageLayout.js
  docs/src/pages/Layouts.mdx
Labels: docs

#3351 fix(Checkbox): prevent `onClick` from being called twice
  src/modules/Checkbox/Checkbox.js
  test/specs/commonTests/isConformant.js
  test/specs/modules/Checkbox/Checkbox-test.js
Labels: ready for review

#3382 chore(tests): make reporter more silent
  karma.conf.babel.js
Labels: chore

#3390 chore(package): upgrade keyboard-key
  package.json
  yarn.lock
Labels: docs, ready for merge, ready for review

#3383 chore(package): update karma and webpack
  .babel-preset.js
  config.js
  karma.conf.babel.js
  package.json
  static.webpack.js
  test/specs/addons/Responsive/Responsive-test.js
  webpack.karma.config.js
  webpack.umd.config.js
  yarn.lock
Labels: chore, ready for review

#3377 feat(Popup): add `disabled` prop
  docs/src/examples/modules/Popup/States/PopupExampleDisabled.js
  docs/src/examples/modules/Popup/States/index.js
  docs/src/examples/modules/Popup/index.js
  src/modules/Popup/Popup.d.ts
  src/modules/Popup/Popup.js
  test/specs/modules/Popup/Popup-test.js
Labels: ready for review

#3399 docs(Examples): add ability to export examples to CodeSandbox
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.js
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleRenderSource.js
  docs/src/components/ComponentDoc/ComponentExample/renderConfig.js
  package.json
  yarn.lock
Labels: docs

#3404 docs(ComponentExample): allow to disable HTML preview
  docs/src/App.js
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.js
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowHtml.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleRenderSource.js
  yarn.lock
Labels: docs

#3405 feat(Ref): add support for forwardRef API
  docs/src/examples/addons/Ref/Types/RefForwardingExample.js
  docs/src/examples/addons/Ref/Types/index.js
  index.d.ts
  package.json
  src/addons/Ref/Ref.d.ts
  src/addons/Ref/Ref.js
  src/addons/Ref/RefFindNode.d.ts
  src/addons/Ref/RefFindNode.js
  src/addons/Ref/RefForward.d.ts
  src/addons/Ref/RefForward.js
  src/index.js
  test/specs/addons/Ref/Ref-test.js
  test/specs/addons/Ref/RefFindNode-test.js
  test/specs/addons/Ref/RefForward-test.js
  test/specs/addons/Ref/fixtures.js
Labels: enhancement

#3407 fix(Portal): fix onBlur handling in IE11
  src/addons/Portal/Portal.js
Labels: ready for merge
