Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2019-08, with the labels that each got.

#3731 chore(AutoControlledComponent): align API of trySetState() with React's
  src/lib/AutoControlledComponent.js
  src/modules/Dropdown/Dropdown.js
  src/modules/Rating/Rating.js
  src/modules/Search/Search.js
  test/specs/lib/AutoControlledComponent-test.js
Labels: chore

#3452 fix(Dropdown): retains focus after selection
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: ready for review

#3732 fix(Checkbox): preventDefault() in mouseDown should prevent focus
  src/modules/Checkbox/Checkbox.js
  test/specs/modules/Checkbox/Checkbox-test.js
Labels: ready for review

#3727 docs(Search): fix wrong description for `input` shorthand
  src/modules/Search/Search.d.ts
  src/modules/Search/Search.js
Labels: docs

#3667 fix(Popup): ignore clicks when `on` prop is set to `hover` only
  src/modules/Popup/Popup.js
Labels: ready for review

#3733 BREAKING(package): require React 16.8
  package.json
  yarn.lock
Labels: breaking-change

#3702 feat(Dropdown): allow selecting an item when pressing the spacebar
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: enhancement

#3752 docs(Usage|Theming): improve pages, introduce CLI util
  docs/src/pages/Theming.mdx
  docs/src/pages/Usage.mdx
Labels: docs

#3754 docs(Popup): add example for `delay` prop in Popup
  docs/src/examples/modules/Popup/Usage/PopupExampleDelay.js
  docs/src/examples/modules/Popup/Usage/index.js
Labels: docs

#3758 docs(CodeSandbox): fix paths for images in exported examples
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox.js
  docs/src/components/ComponentDoc/ComponentControls/createPackageJson.js
  docs/src/components/ComponentDoc/ComponentControls/enhanceExampleCode.js
  docs/src/components/ComponentDoc/ExampleEditor/renderConfig.js
Labels: docs

#3767 docs(Theming): use @semantic-ui-react/craco-less plugin
  docs/src/pages/Theming.mdx
Labels: docs

#3760 feat(Popup): add `positionFixed` to support fixed mode in `Popper.JS`
  src/modules/Popup/Popup.d.ts
  src/modules/Popup/Popup.js
  test/specs/modules/Popup/Popup-test.js
Labels: enhancement, ready for review
