Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2020-09, with the labels that each got.

#4047 fix(Dropdown): handle `text` as a content in `renderLabel`
  src/modules/Dropdown/Dropdown.js
Labels: PR: Bug Fix :bug:

#4060 fix(Transition): schedule changes only on `status` change
  src/modules/Transition/Transition.js
  test/specs/modules/Transition/Transition-test.js
Labels: PR: Bug Fix :bug:

#4029 feat: introduce `children` function to shorthands
  docs/src/pages/ShorthandProps.mdx
  package.json
  src/generic.d.ts
  src/lib/factories.js
  test/specs/lib/factories-test.js
  test/specs/modules/Search/Search-test.js
  test/typings.tsx
Labels: PR: New Feature :rocket:

#4030 fix(Modal|Portal|Popup): use proposed value for `open` in `onOpen` & `onClose` callbacks
  src/addons/Portal/Portal.js
  src/modules/Modal/Modal.js
  src/modules/Popup/Popup.js
  test/specs/addons/Portal/Portal-test.js
  test/specs/modules/Modal/Modal-test.js
  test/specs/modules/Popup/Popup-test.js
Labels: PR: Breaking Change :boom:

#4068 chore: bump update a package with `Ref` component
  package.json
  yarn.lock
Labels: PR: Internal :house:

#4073 chore: remove usages of `lodash/fp` in customPropTypes
  src/collections/Form/FormField.js
  src/elements/Button/Button.js
  src/lib/customPropTypes.js
  test/specs/lib/customPropTypes-test.js
Labels: PR: Internal :house:

#4072 chore: use lodash-es to improve bundle size
  .babel-preset.js
  package.json
  yarn.lock
Labels: PR: Internal :house:

#3947 chore: update `react-popper` to v2
  docs/src/examples/modules/Popup/Usage/PopupExampleOffset.js
  docs/src/examples/modules/Popup/Usage/PopupExampleOffsetFunction.js
  docs/src/examples/modules/Popup/Usage/index.js
  package.json
  src/modules/Popup/Popup.d.ts
  src/modules/Popup/Popup.js
  test/specs/modules/Popup/Popup-test.js
  yarn.lock
Labels: PR: Breaking Change :boom:

#4074 chore: remove Responsive component
  docs/src/examples/addons/Responsive/Types/ResponsiveExampleContent.js
  docs/src/examples/addons/Responsive/Types/ResponsiveExampleMaxWidth.js
  docs/src/examples/addons/Responsive/Types/ResponsiveExampleMinWidth.js
  docs/src/examples/addons/Responsive/Types/ResponsiveExampleMixed.js
  docs/src/examples/addons/Responsive/Types/ResponsiveExampleResponsive.js
  docs/src/examples/addons/Responsive/Types/index.js
  docs/src/examples/addons/Responsive/Usage/ResponsiveExampleBreakpoints.js
  docs/src/examples/addons/Responsive/Usage/ResponsiveExampleFireOnMount.js
  docs/src/examples/addons/Responsive/Usage/ResponsiveExampleOnUpdate.js
  docs/src/examples/addons/Responsive/Usage/index.js
  docs/src/examples/addons/Responsive/index.js
  index.d.ts
  src/addons/Responsive/Responsive.d.ts
  src/addons/Responsive/Responsive.js
  src/addons/Responsive/index.d.ts
  src/addons/Responsive/index.js
  src/addons/Responsive/lib/isVisible.js
  src/index.js
  test/specs/addons/Responsive/Responsive-test.js
Labels: PR: Breaking Change :boom:

#4075 chore: remove MountNode component
  docs/src/examples/addons/MountNode/Types/MountNodeExampleMountNode.js
  docs/src/examples/addons/MountNode/Types/index.js
  docs/src/examples/addons/MountNode/index.js
  index.d.ts
  src/addons/MountNode/MountNode.d.ts
  src/addons/MountNode/MountNode.js
  src/addons/MountNode/index.d.ts
  src/addons/MountNode/index.js
  src/index.js
  test/specs/addons/MountNode/MountNode-test.js
Labels: PR: Breaking Change :boom:

#4076 docs: add migration guide to v2
  docs/public/style.css
  docs/src/components/CodeSnippet/CodeSnippet.js
  docs/src/components/Document.js
  docs/src/components/DocumentationPage/components.js
  docs/src/pages/MigrationGuide.mdx
  docs/src/pages/Prototypes.mdx
Labels: PR: Docs :memo:

#4079 fix(TextArea): update onChange type
  src/addons/TextArea/TextArea.d.ts
Labels: PR: Bug Fix :bug:
