Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2020-07, with the labels that each got.

#3982 chore(Transition): remove deprecated lifecycle methods
  src/addons/TransitionablePortal/TransitionablePortal.js
  src/modules/Transition/Transition.js
  src/modules/Transition/utils/computeStatuses.js
  test/specs/modules/Transition/Transition-test.js
Labels: chore

#3985 chore: use `react-intersection-observer` in docs to improve perf
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  package.json
  yarn.lock
Labels: chore, docs

#3986 chore(Dropdown): remove deprecated lifecycle methods
  src/lib/AutoControlledComponent.js
  src/lib/ModernAutoControlledComponent.js
  src/lib/index.js
  src/modules/Dropdown/Dropdown.js
  src/modules/Dropdown/utils/getMenuOptions.js
  src/modules/Dropdown/utils/getSelectedIndex.js
  test/specs/lib/AutoControlledComponent-test.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: chore

#3958 docs(README.md): fix formatting
  README.md
Labels: docs

#3988 docs: remove knobs usage
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleKnobs.js
  docs/src/components/ComponentDoc/ExampleEditor/renderConfig.js
  docs/src/components/ExternalExampleLayout.js
  docs/src/examples/modules/Popup/Usage/PopupExampleEventsEnabled.js
  docs/src/examples/modules/Sidebar/Examples/SidebarExampleMultiple.js
  docs/src/examples/modules/Sidebar/States/SidebarExampleDimmed.js
  docs/src/examples/modules/Sidebar/Types/SidebarExampleSidebar.js
  docs/src/examples/modules/Sidebar/Usage/SidebarExampleCallback.js
  docs/src/examples/modules/Sidebar/Usage/SidebarExampleTarget.js
  static.config.js
  vercel.json
Labels: docs

#3992 chore: add github action to check PR labels
  .github/workflows/pr-health.yml
Labels: PR: Internal :house:

#3993 chore: use CircleCI workflows [WIP]
  .circleci/config.yml
Labels: PR: Internal :house:

#3901 fix(FormFiled): pass `id` when contains child elements or has `content` prop
  src/collections/Form/FormField.js
  test/specs/collections/Form/FormField-test.js
Labels: PR: Bug Fix :bug:

#3881 docs(LabelExampleImageColored): update example to match image names
  docs/src/examples/elements/Label/Types/LabelExampleImageColored.js
Labels: PR: Docs :memo:

#3995 fix(Accordion): update typings to include `AccordionPanel` on static props
  src/modules/Accordion/Accordion.d.ts
Labels: PR: Bug Fix :bug:

#3996 feat(Flag): include "england" as a valid value
  docs/src/examples/elements/Flag/Types/FlagExampleTable.js
  src/elements/Flag/Flag.js
Labels: PR: New Feature :rocket:

#3997 docs(SidebarExampleTransitions): fix look of the example
  docs/src/examples/.eslintrc
  docs/src/examples/modules/Sidebar/Examples/SidebarExampleTransitions.js
Labels: PR: Docs :memo:

#3898 docs(README): correct webpack example link
  README.md
Labels: PR: Docs :memo:

#3998 fix(Portal): throw an error if React.Fragment passed as `trigger`
  src/addons/Portal/Portal.js
  src/addons/Portal/utils/validateTrigger.js
  src/modules/Popup/Popup.js
  test/specs/addons/Portal/Portal-test.js
  test/specs/addons/Portal/utils/validateTrigger-test.js
Labels: PR: Bug Fix :bug:

#3999 chore: add bundle size metrics
  .github/workflows/size-limit.yml
  .size-limit.js
  bundle-size/bundle.js
  bundle-size/fixtures/Button.size.js
  bundle-size/fixtures/Icon.size.js
  bundle-size/fixtures/Image.size.js
  bundle-size/fixtures/Portal.size.js
  package.json
  yarn.lock
Labels: PR: Internal :house:

#3785 fix(Search): merge nested shorthand props for the <input> element
  src/modules/Search/Search.js
  test/specs/modules/Search/Search-test.js
Labels: PR: Bug Fix :bug:

#4001 chore: bump dependencies, minor fixes
  .babel-preset.js
  docs/src/components/CodeSnippet/CodeSnippet.js
  docs/src/components/CodeSnippet/CodeSnippetLabel.js
  docs/src/components/CodeSnippet/index.js
  docs/src/components/ComponentDoc/ExampleEditor/ExampleEditorMenu.js
  docs/src/components/CopyToClipboard.js
  docs/src/components/Document.js
  docs/src/components/DocumentationPage/components.js
  docs/src/pages/Theming.mdx
  package.json
  static.config.js
  static.webpack.js
  yarn.lock
Labels: PR: Internal :house:

#3713 docs: make get started instructions around themes more clear
  docs/src/components/CodeSnippet/CodeSnippet.js
  docs/src/pages/Usage.mdx
Labels: PR: Docs :memo:

#3938 fix(Search): fix an error when `showNoResults=false` and arrow down is pressed
  src/modules/Search/Search.js
Labels: PR: Bug Fix :bug:

#3964 docs(TableExampleSortable): your description
  docs/src/examples/collections/Table/Variations/TableExampleSortable.js
Labels: PR: Docs :memo:

#3957 docs(Tab): add note that `grid` prop only applies to vertical menu
  src/modules/Tab/Tab.js
Labels: PR: Docs :memo:

#4004 fix(Dropdown): handle keyboard events for arrows, space and enter keys locally
  docs/src/examples/modules/Dropdown/States/DropdownExampleDisabledItem.js
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: PR: Bug Fix :bug:

#4006 fix(Dropdown): compute proper `selectedIndex` in `multiple`
  src/modules/Dropdown/utils/getSelectedIndex.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: PR: Bug Fix :bug:

#4003 feat(Dropdown): add support for images, icons and flags in selected values
  docs/src/examples/modules/Dropdown/Types/DropdownExampleClearableMultiple.js
  src/index.js
  src/modules/Dropdown/Dropdown.js
  src/modules/Dropdown/DropdownText.d.ts
  src/modules/Dropdown/DropdownText.js
  test/specs/modules/Dropdown/Dropdown-test.js
  test/specs/modules/Dropdown/DropdownText-test.js
Labels: PR: New Feature :rocket:

#4009 docs: fix IE11 issues
  docs/src/components/CodeSnippet/CodeSnippet.js
  docs/src/components/Document.js
  docs/src/utils/formatCode.js
  static.config.js
  static.webpack.js
Labels: PR: Internal :house:

#4008 docs(Responsive): deprecate component
  docs/src/components/ComponentDoc/ComponentDoc.js
  docs/src/examples/addons/Responsive/index.js
  docs/src/layouts/HomepageLayout.js
  package.json
  src/addons/Responsive/Responsive.js
  static.routes.js
  test/specs/addons/Responsive/Responsive-test.js
  yarn.lock
Labels: PR: Docs :memo:

#4010 docs: improve CodeSandbox integration
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox.js
  docs/src/components/ComponentDoc/ComponentControls/createPackageJson.js
  docs/src/components/ComponentDoc/ComponentControls/enhanceExampleCode.js
  docs/src/components/ComponentDoc/ExampleEditor/renderConfig.js
Labels: PR: Docs :memo:

#4014 fix(Dropdown): update search prop typing
  src/modules/Dropdown/Dropdown.d.ts
Labels: PR: Bug Fix :bug:
