Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2020-08, with the labels that each got.

#4019 fix(Popup|Visibility): update types definitions for props
  src/behaviors/Visibility/Visibility.d.ts
  src/modules/Popup/Popup.d.ts
Labels: PR: Bug Fix :bug:

#4018 fix(Dropdown): update typings for `defaultValue` & `value`
  src/modules/Dropdown/Dropdown.d.ts
Labels: PR: Bug Fix :bug:

#3795 docs(SearchExampleStandardCustom): use React hooks
  docs/src/examples/modules/Search/Types/SearchExampleStandardCustom.js
Labels: PR: Docs :memo:

#3794 docs(SearchExampleStandard): use React hooks
  docs/src/examples/modules/Search/Types/SearchExampleStandard.js
Labels: PR: Docs :memo:

#1739 feat(Modal): impliment Dimmer shorthand
  index.d.ts
  src/index.js
  src/modules/Modal/Modal.d.ts
  src/modules/Modal/Modal.js
  src/modules/Modal/ModalDimmer.d.ts
  src/modules/Modal/ModalDimmer.js
  src/modules/Modal/ModalHeader.js
  test/specs/modules/Modal/Modal-test.js
  test/specs/modules/Modal/ModalDimmer-test.js
Labels: PR: New Feature :rocket:

#4026 fix(Popup): do not throw if `context` & `trigger` are missing
  docs/src/examples/modules/Popup/Usage/PopupExampleContext.js
  docs/src/examples/modules/Popup/Usage/PopupExampleContextControlled.js
  docs/src/examples/modules/Popup/Usage/PopupExampleContextMenu.js
  docs/src/examples/modules/Popup/Usage/index.js
  src/modules/Popup/lib/createReferenceProxy.js
Labels: PR: Bug Fix :bug:

#4027 chore(MountNode): deprecate component
  docs/src/examples/addons/MountNode/index.js
  src/addons/MountNode/MountNode.js
  src/addons/MountNode/lib/NodeRegistry.js
  src/addons/MountNode/lib/computeClassNames.js
  src/addons/MountNode/lib/computeClassNamesDifference.js
  src/addons/MountNode/lib/getNodeRefFromProps.js
  src/addons/MountNode/lib/handleClassNamesChange.js
  src/lib/hooks/useClassNamesOnNode.js
  src/lib/hooks/useIsomorphicLayoutEffect.js
  src/lib/index.js
  src/modules/Modal/ModalDimmer.js
  test/specs/addons/MountNode/MountNode-test.js
  test/specs/addons/MountNode/lib/computeClassNameDifference-test.js
  test/specs/addons/MountNode/lib/getNodeRefFromProps-test.js
  test/specs/lib/hooks/NodeRegistry-test.js
  test/specs/lib/hooks/computeClassNameDifference-test.js
  test/specs/lib/hooks/computeClassNames-test.js
  test/specs/lib/hooks/handleClassNamesChange-test.js
  test/specs/lib/hooks/useClassNamesOnNode-test.js
  test/specs/modules/Modal/Modal-test.js
  test/specs/modules/Modal/ModalDimmer-test.js
Labels: PR: Internal :house:

#4037 fix(Pagination): set a default activePage in Pagination's state
  src/addons/Pagination/Pagination.js
  test/specs/addons/Pagination/Pagination-test.js
Labels: PR: Bug Fix :bug:

#4023 chore: update Ref dependency to latest version
  index.d.ts
  package.json
  src/addons/Portal/Portal.js
  src/addons/Portal/PortalInner.js
  src/addons/TextArea/TextArea.js
  src/behaviors/Visibility/Visibility.js
  src/elements/Button/Button.js
  src/elements/Input/Input.js
  src/index.js
  src/lib/hooks/useClassNamesOnNode.js
  src/modules/Checkbox/Checkbox.js
  src/modules/Dimmer/DimmerInner.js
  src/modules/Dropdown/Dropdown.js
  src/modules/Modal/Modal.js
  src/modules/Modal/ModalDimmer.js
  src/modules/Popup/Popup.js
  src/modules/Popup/lib/createReferenceProxy.js
  src/modules/Sidebar/Sidebar.js
  src/modules/Sticky/Sticky.js
  test/specs/modules/Sidebar/Sidebar-test.js
  test/utils/nestedShallow.js
  yarn.lock
Labels: PR: Internal :house:, needs author feedback

#4039 docs(Ref): restore docs for a component
  docs/src/components/ComponentDoc/ComponentDoc.js
  docs/src/examples/addons/Ref/Types/RefExampleRef.js
  docs/src/examples/addons/Ref/Types/RefForwardingExample.js
  docs/src/examples/addons/Ref/Types/index.js
  docs/src/examples/addons/Ref/index.js
  docs/static/utils/getComponentMenu.js
  src/modules/Popup/lib/createReferenceProxy.js
  static.routes.js
  test/specs/modules/Popup/lib/createReferenceProxy-test.js
Labels: PR: Docs :memo:

#4040 docs(Placeholder): fix description of the component
  src/elements/Placeholder/Placeholder.js
Labels: PR: Docs :memo:

#4041 fix(Dropdown): fix handling of "Space" key
  .babel-preset.js
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: PR: Bug Fix :bug:

#4043 fix(FormField): fix aria-invalid on error false
  src/collections/Form/FormField.js
  test/specs/collections/Form/FormField-test.js
Labels: PR: Bug Fix :bug:
