Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2021-07, with the labels that each got.

#4221 docs(Usage): update "CDN (no bundler)" section
  docs/src/pages/Usage.mdx
Labels: PR: Docs :memo:

#4232 chore: remove .state() assertions in tests
  src/modules/Embed/Embed.js
  src/modules/Transition/Transition.js
  test/specs/addons/TransitionablePortal/TransitionablePortal-test.js
  test/specs/modules/Accordion/AccordionAccordion-test.js
  test/specs/modules/Checkbox/Checkbox-test.js
  test/specs/modules/Dropdown/Dropdown-test.js
  test/specs/modules/Embed/Embed-test.js
  test/specs/modules/Transition/Transition-test.js
Labels: PR: Internal :house:

#4234 chore(Image): use React.forwardRef()
  docs/src/utils/docTypes/componentInfoShape.js
  gulp/plugins/util/getComponentInfo.js
  src/elements/Image/Image.js
  src/lib/factories.js
  test/specs/commonTests/forwardsRef.js
  test/specs/commonTests/hasValidTypings.js
  test/specs/commonTests/implementsCreateMethod.js
  test/specs/commonTests/index.js
  test/specs/commonTests/isConformant.js
  test/specs/elements/Image/Image-test.js
  test/utils/getComponentName.js
  test/utils/getComponentProps.js
  test/utils/index.js
Labels: PR: Internal :house:

#4236 chore(Placeholder): use React.forwardRef()
  src/elements/Placeholder/Placeholder.js
  src/elements/Placeholder/PlaceholderHeader.js
  src/elements/Placeholder/PlaceholderImage.js
  src/elements/Placeholder/PlaceholderLine.js
  src/elements/Placeholder/PlaceholderParagraph.js
  test/specs/commonTests/isConformant.js
  test/specs/elements/Placeholder/Placeholder-test.js
  test/specs/elements/Placeholder/PlaceholderHeader-test.js
  test/specs/elements/Placeholder/PlaceholderImage-test.js
  test/specs/elements/Placeholder/PlaceholderLine-test.js
  test/specs/elements/Placeholder/PlaceholderParagraph-test.js
Labels: PR: Internal :house:

#4237 chore(Header): use React.forwardRef()
  src/elements/Header/Header.js
  src/elements/Header/HeaderContent.js
  src/elements/Header/HeaderSubheader.js
  test/specs/elements/Header/Header-test.js
  test/specs/elements/Header/HeaderContent-test.js
  test/specs/elements/Header/HeaderSubheader-test.js
Labels: PR: Internal :house:

#4238 chore(Segment): use React.forwardRef()
  src/elements/Segment/Segment.js
  src/elements/Segment/SegmentGroup.js
  src/elements/Segment/SegmentInline.js
  test/specs/elements/Segment/Segment-test.js
  test/specs/elements/Segment/SegmentGroup-test.js
  test/specs/elements/Segment/SegmentInline-test.js
Labels: PR: Internal :house:

#4239 chore(Table): use React.forwardRef()
  src/collections/Table/Table.js
  src/collections/Table/TableBody.js
  src/collections/Table/TableCell.js
  src/collections/Table/TableFooter.js
  src/collections/Table/TableHeader.js
  src/collections/Table/TableHeaderCell.js
  src/collections/Table/TableRow.js
  test/specs/collections/Table/Table-test.js
  test/specs/collections/Table/TableBody-test.js
  test/specs/collections/Table/TableCell-test.js
  test/specs/collections/Table/TableFooter-test.js
  test/specs/collections/Table/TableHeader-test.js
  test/specs/collections/Table/TableHeaderCell-test.js
  test/specs/collections/Table/TableRow-test.js
  test/specs/commonTests/forwardsRef.js
  test/specs/elements/Header/Header-test.js
Labels: PR: Internal :house:

#4240 chore(Step): use React.forwardRef()
  src/elements/Step/Step.js
  src/elements/Step/StepContent.js
  src/elements/Step/StepDescription.js
  src/elements/Step/StepGroup.js
  src/elements/Step/StepTitle.js
  src/lib/hooks/useEventCallback.js
  src/lib/index.js
  test/specs/addons/Confirm/Confirm-test.js
  test/specs/addons/TransitionablePortal/TransitionablePortal-test.js
  test/specs/collections/Form/FormInput-test.js
  test/specs/commonTests/forwardsRef.js
  test/specs/commonTests/isConformant.js
  test/specs/elements/Step/Step-test.js
  test/specs/elements/Step/StepContent-test.js
  test/specs/elements/Step/StepDescription-test.js
  test/specs/elements/Step/StepGroup-test.js
  test/specs/elements/Step/StepTitle-test.js
Labels: PR: Internal :house:

#4241 chore: disable ESLint rule for function names
  .eslintrc
  src/collections/Table/Table.js
  src/collections/Table/TableBody.js
  src/collections/Table/TableCell.js
  src/collections/Table/TableFooter.js
  src/collections/Table/TableHeader.js
  src/collections/Table/TableHeaderCell.js
  src/collections/Table/TableRow.js
  src/elements/Header/Header.js
  src/elements/Header/HeaderContent.js
  src/elements/Header/HeaderSubheader.js
  src/elements/Image/Image.js
  src/elements/Placeholder/Placeholder.js
  src/elements/Placeholder/PlaceholderHeader.js
  src/elements/Placeholder/PlaceholderImage.js
  src/elements/Placeholder/PlaceholderLine.js
  src/elements/Placeholder/PlaceholderParagraph.js
  src/elements/Segment/Segment.js
  src/elements/Segment/SegmentGroup.js
  src/elements/Segment/SegmentInline.js
  src/elements/Step/Step.js
  src/elements/Step/StepContent.js
  src/elements/Step/StepDescription.js
  src/elements/Step/StepGroup.js
  src/elements/Step/StepTitle.js
  test/specs/commonTests/forwardsRef.js
Labels: PR: Internal :house:

#4242 chore(Comment): use React.forwardRef()
  src/views/Comment/Comment.js
  src/views/Comment/CommentAction.js
  src/views/Comment/CommentActions.js
  src/views/Comment/CommentAuthor.js
  src/views/Comment/CommentAvatar.js
  src/views/Comment/CommentContent.js
  src/views/Comment/CommentGroup.js
  src/views/Comment/CommentMetadata.js
  src/views/Comment/CommentText.js
  test/specs/views/Comment/Comment-test.js
  test/specs/views/Comment/CommentAction-test.js
  test/specs/views/Comment/CommentActions-test.js
  test/specs/views/Comment/CommentAuthor-test.js
  test/specs/views/Comment/CommentAvatar-test.js
  test/specs/views/Comment/CommentContent-test.js
  test/specs/views/Comment/CommentGroup-test.js
  test/specs/views/Comment/CommentMetadata-test.js
  test/specs/views/Comment/CommentText-test.js
Labels: PR: Internal :house:

#4243 chore(Card): use React.forwardRef()
  src/views/Card/Card.js
  src/views/Card/CardContent.js
  src/views/Card/CardDescription.js
  src/views/Card/CardGroup.js
  src/views/Card/CardHeader.js
  src/views/Card/CardMeta.js
  test/specs/views/Card/Card-test.js
  test/specs/views/Card/CardContent-test.js
  test/specs/views/Card/CardDescription-test.js
  test/specs/views/Card/CardGroup-test.js
  test/specs/views/Card/CardHeader-test.js
  test/specs/views/Card/CardMeta-test.js
Labels: PR: Internal :house:

#4244 chore(Feed): use React.forwardRef()
  src/views/Feed/Feed.js
  src/views/Feed/FeedContent.js
  src/views/Feed/FeedDate.js
  src/views/Feed/FeedEvent.js
  src/views/Feed/FeedExtra.js
  src/views/Feed/FeedLabel.js
  src/views/Feed/FeedLike.js
  src/views/Feed/FeedMeta.js
  src/views/Feed/FeedSummary.js
  src/views/Feed/FeedUser.js
  test/specs/views/Card/Card-test.js
  test/specs/views/Feed/Feed-test.js
  test/specs/views/Feed/FeedContent-test.js
  test/specs/views/Feed/FeedDate-test.js
  test/specs/views/Feed/FeedEvent-test.js
  test/specs/views/Feed/FeedExtra-test.js
  test/specs/views/Feed/FeedLabel-test.js
  test/specs/views/Feed/FeedLike-test.js
  test/specs/views/Feed/FeedMeta-test.js
  test/specs/views/Feed/FeedSummary-test.js
  test/specs/views/Feed/FeedUser-test.js
Labels: PR: Internal :house:

#4245 chore(Statistic): use React.forwardRef()
  src/views/Statistic/Statistic.js
  src/views/Statistic/StatisticGroup.js
  src/views/Statistic/StatisticLabel.js
  src/views/Statistic/StatisticValue.js
  test/specs/views/Stastistic/Statistic-test.js
  test/specs/views/Stastistic/StatisticGroup-test.js
  test/specs/views/Stastistic/StatisticLabel-test.js
  test/specs/views/Stastistic/StatisticValue-test.js
Labels: PR: Internal :house:

#4228 docs(Introduction): Update broken link for renamed component AutoControlledComponent
  docs/src/pages/Introduction.js
Labels: PR: Docs :memo:

#4247 chore(Item): use React.forwardRef()
  src/views/Item/Item.js
  src/views/Item/ItemContent.js
  src/views/Item/ItemDescription.js
  src/views/Item/ItemExtra.js
  src/views/Item/ItemGroup.js
  src/views/Item/ItemHeader.js
  src/views/Item/ItemImage.d.ts
  src/views/Item/ItemImage.js
  src/views/Item/ItemMeta.js
  test/specs/views/Item/Item-test.js
  test/specs/views/Item/ItemContent-test.js
  test/specs/views/Item/ItemDescription-test.js
  test/specs/views/Item/ItemExtra-test.js
  test/specs/views/Item/ItemGroup-test.js
  test/specs/views/Item/ItemHeader-test.js
  test/specs/views/Item/ItemImage-test.js
  test/specs/views/Item/ItemMeta-test.js
Labels: PR: Internal :house:

#4248 chore(Container|Divider|Loader|Rail): use React.forwardRef()
  src/elements/Container/Container.js
  src/elements/Divider/Divider.js
  src/elements/Loader/Loader.js
  src/elements/Rail/Rail.js
  test/specs/elements/Container/Container-test.js
  test/specs/elements/Divider/Divider-test.js
  test/specs/elements/Loader/Loader-test.js
  test/specs/elements/Rail/Rail-test.js
Labels: PR: Internal :house:

#4249 chore(Accordion): use React.forwardRef()
  src/lib/hooks/useAutoControlledValue.js
  src/lib/index.js
  src/modules/Accordion/Accordion.js
  src/modules/Accordion/AccordionAccordion.js
  src/modules/Accordion/AccordionContent.js
  src/modules/Accordion/AccordionTitle.js
  test/specs/modules/Accordion/Accordion-test.js
  test/specs/modules/Accordion/AccordionAccordion-test.js
  test/specs/modules/Accordion/AccordionContent-test.js
  test/specs/modules/Accordion/AccordionTitle-test.js
Labels: PR: Internal :house:

#4250 chore(Advertisement|Breadcrumb): use React.forwardRef()
  src/collections/Breadcrumb/Breadcrumb.js
  src/collections/Breadcrumb/BreadcrumbDivider.js
  src/collections/Breadcrumb/BreadcrumbSection.js
  src/views/Advertisement/Advertisement.js
  test/specs/collections/Breadcrumb/Breadcrumb-test.js
  test/specs/collections/Breadcrumb/BreadcrumbDivider-test.js
  test/specs/collections/Breadcrumb/BreadcrumbSection-test.js
Labels: PR: Internal :house:

#4251 chore(Message): use React.forwardRef()
  src/collections/Message/Message.js
  src/collections/Message/MessageContent.js
  src/collections/Message/MessageHeader.js
  src/collections/Message/MessageItem.js
  src/collections/Message/MessageList.js
  test/specs/collections/Message/Message-test.js
  test/specs/collections/Message/MessageContent-test.js
  test/specs/collections/Message/MessageHeader-test.js
  test/specs/collections/Message/MessageItem-test.js
  test/specs/collections/Message/MessageList-test.js
Labels: PR: Internal :house:

#4252 chore(Label|List): use React.forwardRef()
  src/elements/Label/Label.js
  src/elements/Label/LabelDetail.js
  src/elements/Label/LabelGroup.js
  src/elements/List/List.js
  src/elements/List/ListContent.js
  src/elements/List/ListDescription.js
  src/elements/List/ListHeader.js
  src/elements/List/ListIcon.js
  src/elements/List/ListItem.js
  src/elements/List/ListList.js
  test/specs/elements/Label/Label-test.js
  test/specs/elements/Label/LabelDetail-test.js
  test/specs/elements/Label/LabelGroup-test.js
  test/specs/elements/List/List-test.js
  test/specs/elements/List/ListContent-test.js
  test/specs/elements/List/ListDescription-test.js
  test/specs/elements/List/ListHeader-test.js
  test/specs/elements/List/ListItem-test.js
  test/specs/elements/List/ListList-test.js
Labels: PR: Internal :house:

#4254 chore(Menu): use React.forwardRef()
  src/collections/Menu/Menu.js
  src/collections/Menu/MenuHeader.js
  src/collections/Menu/MenuItem.js
  src/collections/Menu/MenuMenu.js
  test/specs/collections/Menu/Menu-test.js
  test/specs/collections/Menu/MenuHeader-test.js
  test/specs/collections/Menu/MenuItem-test.js
  test/specs/collections/Menu/MenuMenu-test.js
Labels: PR: Internal :house:

#4255 chore(Pagination): use React.forwardRef()
  src/addons/Pagination/Pagination.js
  src/addons/Pagination/PaginationItem.js
  test/specs/addons/Pagination/Pagination-test.js
  test/specs/addons/Pagination/PaginationItem-test.js
Labels: PR: Internal :house:

#4256 chore(Button): use React.forwardRef()
  src/elements/Button/Button.js
  src/elements/Button/ButtonContent.js
  src/elements/Button/ButtonGroup.js
  src/elements/Button/ButtonOr.js
  src/lib/hooks/useMergedRefs.js
  src/lib/index.js
  test/specs/elements/Button/Button-test.js
  test/specs/elements/Button/ButtonContent-test.js
  test/specs/elements/Button/ButtonGroup-test.js
  test/specs/elements/Button/ButtonOr-test.js
Labels: PR: Internal :house:

#4253 chore(Modal|Portal|Popup): use React.forwardRef()
  src/addons/Portal/Portal.js
  src/addons/Portal/PortalInner.js
  src/addons/Portal/usePortalElement.js
  src/addons/Portal/utils/useTrigger.js
  src/addons/Portal/utils/validateTrigger.js
  src/lib/doesNodeContainClick.js
  src/lib/hooks/useAutoControlledValue.js
  src/lib/hooks/usePrevious.js
  src/lib/index.js
  src/modules/Modal/Modal.js
  src/modules/Modal/ModalDimmer.js
  src/modules/Popup/Popup.js
  test/specs/addons/Portal/Portal-test.js
  test/specs/addons/Portal/PortalInner-test.js
  test/specs/modules/Modal/Modal-test.js
  test/specs/modules/Popup/Popup-test.js
Labels: PR: Internal :house:, blocked

#4258 chore(Rating|Reveal): use React.forwardRef()
  src/elements/Reveal/Reveal.js
  src/elements/Reveal/RevealContent.js
  src/modules/Rating/Rating.js
  src/modules/Rating/RatingIcon.js
  test/specs/elements/Reveal/Reveal-test.js
  test/specs/elements/Reveal/RevealContent-test.js
  test/specs/modules/Rating/Rating-test.js
  test/specs/modules/Rating/RatingIcon-test.js
Labels: PR: Internal :house:

#4259 fix(Modal|Portal): fix an error with unsafe setState()
  src/addons/Portal/Portal.js
  src/modules/Modal/Modal.js
  test/specs/modules/Modal/Modal-test.js
Labels: PR: Bug Fix :bug:

#4260 chore(Dimmer|Grid|Sidebar): use React.forwardRef()
  src/collections/Grid/Grid.js
  src/collections/Grid/GridColumn.js
  src/collections/Grid/GridRow.js
  src/modules/Dimmer/Dimmer.js
  src/modules/Dimmer/DimmerDimmable.js
  src/modules/Dimmer/DimmerInner.js
  src/modules/Sidebar/Sidebar.js
  src/modules/Sidebar/SidebarPushable.js
  src/modules/Sidebar/SidebarPusher.js
  test/specs/collections/Grid/Grid-test.js
  test/specs/collections/Grid/GridColumn-test.js
  test/specs/collections/Grid/GridRow-test.js
  test/specs/modules/Dimmer/Dimmer-test.js
  test/specs/modules/Dimmer/DimmerDimmable-test.js
  test/specs/modules/Dimmer/DimmerInner-test.js
  test/specs/modules/Sidebar/Sidebar-test.js
  test/specs/modules/Sidebar/SidebarPushable-test.js
  test/specs/modules/Sidebar/SidebarPusher-test.js
Labels: PR: Internal :house:

#4261 chore(Modal*|Popup*): use React.forwardRef()
  src/modules/Modal/ModalActions.js
  src/modules/Modal/ModalContent.js
  src/modules/Modal/ModalDescription.js
  src/modules/Modal/ModalHeader.js
  src/modules/Popup/PopupContent.js
  src/modules/Popup/PopupHeader.js
  test/specs/modules/Modal/ModalActions-test.js
  test/specs/modules/Modal/ModalContent-test.js
  test/specs/modules/Modal/ModalDescription-test.js
  test/specs/modules/Modal/ModalDimmer-test.js
  test/specs/modules/Modal/ModalHeader-test.js
  test/specs/modules/Popup/PopupContent-test.js
  test/specs/modules/Popup/PopupHeader-test.js
Labels: PR: Internal :house:

#4262 chore(Confirm|Checkbox|Embed|Radio|TextArea): use React.forwardRef()
  src/addons/Confirm/Confirm.js
  src/addons/Radio/Radio.js
  src/addons/TextArea/TextArea.js
  src/modules/Checkbox/Checkbox.js
  src/modules/Embed/Embed.js
  src/modules/Progress/Progress.js
  test/specs/addons/Radio/Radio-test.js
  test/specs/addons/TextArea/TextArea-test.js
  test/specs/modules/Checkbox/Checkbox-test.js
  test/specs/modules/Embed/Embed-test.js
  test/specs/modules/Progress/Progress-test.js
Labels: PR: Internal :house:

#4264 chore(Flag|Icon|ImageGroup): use React.forwardRef()
  src/elements/Flag/Flag.js
  src/elements/Icon/Icon.js
  src/elements/Icon/IconGroup.js
  src/elements/Image/ImageGroup.js
  test/specs/commonTests/forwardsRef.js
  test/specs/commonTests/implementsShorthandProp.js
  test/specs/elements/Flag/Flag-test.js
  test/specs/elements/Icon/Icon-test.js
  test/specs/elements/Image/ImageGroup-test.js
  test/specs/elements/Input/Input-test.js
  test/specs/elements/Label/Label-test.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: PR: Internal :house:

#4265 chore(Tab): use React.forwardRef()
  src/modules/Tab/Tab.js
  src/modules/Tab/TabPane.js
  test/specs/modules/Tab/Tab-test.js
  test/specs/modules/Tab/TabPane-test.js
Labels: PR: Internal :house:

#4266 chore(TransitionGroup): use React.forwardRef()
  src/modules/Transition/Transition.js
  src/modules/Transition/TransitionGroup.js
  test/specs/modules/Transition/TransitionGroup-test.js
Labels: PR: Internal :house:

#4267 chore(Input): use React.forwardRef()
  src/elements/Input/Input.js
  src/lib/hooks/useMergedRefs.js
  src/lib/index.js
  test/specs/elements/Input/Input-test.js
Labels: PR: Internal :house:

#4263 chore(Sticky): use React.forwardRef()
  src/modules/Sticky/Sticky.js
  test/specs/modules/Sticky/Sticky-test.js
Labels: PR: Internal :house:
