Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2021-08, with the labels that each got.

#4181 fix(Dropdown): update event types
  src/modules/Dropdown/Dropdown.d.ts
Labels: PR: Bug Fix :bug:

#4269 chore(TransitionablePortal): convert to be functional component
  src/addons/TransitionablePortal/TransitionablePortal.js
  src/lib/hooks/useForceUpdate.js
  src/lib/index.js
  src/modules/Sidebar/Sidebar.js
  src/modules/Transition/TransitionGroup.js
  test/specs/addons/TransitionablePortal/TransitionablePortal-test.js
Labels: PR: Internal :house:

#4273 chore(Dropdown*): use React.forwardRef()
  src/modules/Dropdown/DropdownDivider.js
  src/modules/Dropdown/DropdownHeader.js
  src/modules/Dropdown/DropdownItem.js
  src/modules/Dropdown/DropdownMenu.js
  src/modules/Dropdown/DropdownSearchInput.js
  src/modules/Dropdown/DropdownText.js
  test/specs/docs/examples-test.js
  test/specs/modules/Dropdown/DropdownDivider-test.js
  test/specs/modules/Dropdown/DropdownHeader-test.js
  test/specs/modules/Dropdown/DropdownItem-test.js
  test/specs/modules/Dropdown/DropdownMenu-test.js
  test/specs/modules/Dropdown/DropdownSearchInput-test.js
  test/specs/modules/Dropdown/DropdownText-test.js
Labels: PR: Internal :house:

#4275 fix(types): export types for StrictBreadcrumbProps & StrictSelectProps
  index.d.ts
Labels: PR: Bug Fix :bug:

#4153 docs(Input): Include an example for passing props to input element
  docs/src/examples/elements/Input/Usage/InputExampleInputElementProps.js
  docs/src/examples/elements/Input/Usage/index.js
Labels: PR: Docs :memo:
