Repository Semantic-Org/Semantic-UI-React, pull requests merged in 2022-01, with the labels that each got.

#4278 docs(MenuExampleStackable): Adding alt for logo
  docs/src/examples/collections/Menu/Variations/MenuExampleStackable.js
Labels: PR: Docs :memo:

#4309 fix(Search): type definition for layout renderer
  src/modules/Search/Search.d.ts
  src/modules/Search/SearchCategory.d.ts
Labels: PR: Bug Fix :bug:

#4316 chore: bump Percy, Puppeteer & caniuse-lite
  cypress/plugins/index.js
  package.json
  yarn.lock
Labels: PR: Internal :house:

#4282 feat(Search): add "placeholder" & documentation
  docs/src/examples/modules/Search/Types/SearchExampleStandard.js
  src/modules/Search/Search.d.ts
  src/modules/Search/Search.js
  test/specs/modules/Search/Search-test.js
Labels: PR: New Feature :rocket:

#4291 docs(Modal): update props' description
  src/modules/Modal/Modal.js
Labels: PR: Docs :memo:

#4317 docs(TextArea): fix verbiage in TextArea docs
  docs/src/examples/addons/TextArea/Usage/index.js
Labels: PR: Docs :memo:

#4321 fix(Button): handle `type` properly
  src/collections/Form/FormButton.d.ts
  src/elements/Button/Button.d.ts
  src/elements/Button/Button.js
  test/specs/elements/Button/Button-test.js
Labels: PR: Bug Fix :bug:

#4319 docs(Modal): fix minor confirm modal typo
  src/addons/Confirm/Confirm.js
Labels: PR: Docs :memo:

#4322 fix(Dropdown): handle "onClick" on options
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: PR: Bug Fix :bug:

#4199 fix(Dropdown): do not select disabled items on blur
  src/modules/Dropdown/Dropdown.js
  test/specs/modules/Dropdown/Dropdown-test.js
Labels: PR: Bug Fix :bug:

#4324 docs(Visibility|Ref): deprecate components
  docs/src/examples/addons/Ref/index.js
  docs/src/examples/behaviors/Visibility/index.js
  src/behaviors/Visibility/Visibility.js
  static.routes.js
Labels: PR: Docs :memo:

#4327 fix(Search): remove "placeholder" from "defaultProps"
  src/modules/Search/Search.js
Labels: PR: Bug Fix :bug:

#4328 docs(Checkbox): minor rework to use hooks, better show controlled mode
  docs/src/examples/modules/Checkbox/Types/CheckboxExampleRadioGroup.js
  docs/src/examples/modules/Checkbox/Usage/CheckboxExampleRemoteControl.js
Labels: PR: Docs :memo:
